using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace BGU.DRPL.SignificantOwnership.Core.Spares.Dict
{
    /// <summary>
    /// Запис типу міжнародного класифікатора професій 
    /// (ISCO - international standard classification of occupations)
    /// Список вибудовано за резолюцією від 3-6.12.2007 - 
    /// http://www.ilo.org/public/english/bureau/stat/isco/docs/resol08.pdf
    /// Професія за версією українського класифікатора професій
    /// Джерело: КЛАСИФІКАТОР ПРОФЕСІЙ
    /// ДК 003:2010 
    /// ЗАТВЕРДЖЕНО ТА НАДАНО ЧИННОСТІ
    /// Наказ Держспоживстандарту України
    /// 28.07.2010 N 327 
    /// Чинний від 01.11.2010 р.
    /// Оригінал стандарту: http://www.ilo.org/public/english/bureau/stat/isco/
    /// </summary>
    /// <seealso cref="http://hrliga.com/docs/327_KP.htm"/>
    public class ISCO : NotifyPropertyChangedBase
    {
        #region prop(s)
        private string _OccupID; 
        [DisplayName("Код професії/групи")]
        [Description("Код професії чи групи професій")]
        public string OccupID { get { return _OccupID; } set { _OccupID = value; OnPropertyChanged("OccupID"); } }

        private string _ParentOccupID;
        [DisplayName("Код групи")]
        [Description("Код групи професій, до якої відноситься дана професія")]
        public string ParentOccupID { get { return _ParentOccupID; } set { _ParentOccupID = value; OnPropertyChanged("ParentOccupID"); } }

        private string _OccupName;
        [DisplayName("Назва професії/групи")]
        [Description("Назва професії чи групи професій (оригінальне написання англ., згідно стандарту)")]
        public string OccupName { get { return _OccupName; } set { _OccupName = value; OnPropertyChanged("OccupName"); } }
        private string _OccupNameUkr;
        [DisplayName("Назва професії/групи (укр.)")]
        [Description("Переклад назви професії чи групи професій українською")]
        public string OccupNameUkr { get { return _OccupNameUkr; } set { _OccupNameUkr = value; OnPropertyChanged("OccupNameUkr"); } }
        #endregion

        #region static members
        private static readonly List<ISCO> _AllCodes;
        
        #region cctor
        static ISCO()
        {
            _AllCodes = new List<ISCO>();
            #region fill
            _AllCodes.Add(new ISCO() { OccupID = "1", OccupName = "Managers", OccupNameUkr = "Керівники", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "2", OccupName = "Professionals", OccupNameUkr = "Фахівці", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "3", OccupName = "Technicians and associate professionals", OccupNameUkr = "Технічні та пов'язані з ними професії", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "4", OccupName = "Clerical support workers", OccupNameUkr = "Допоміжні офісні працівники", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "5", OccupName = "Service and sales workers", OccupNameUkr = "Обслуговуючий та торгівельний персонал", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "6", OccupName = "Skilled agricultural, forestry and fishery workers", OccupNameUkr = "Кваліфіковані працівники сільського, лісового та рибного господарства", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "7", OccupName = "Craft and related trades workers", OccupNameUkr = "Працівники ремесел то схожих професій", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "8", OccupName = "Plant and machine operators, and assemblers", OccupNameUkr = "Оператори заводів та машин, збірники", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "9", OccupName = "Elementary occupations", OccupNameUkr = "Елементарні заняття", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "0", OccupName = "Armed forces occupations", OccupNameUkr = "Елементарні заняття", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "11", OccupName = "Chief executives, senior officials and legislators", OccupNameUkr = "Керівники найвищого та вищого рівня, а також законодавці", ParentOccupID = "1" });
            _AllCodes.Add(new ISCO() { OccupID = "12", OccupName = "Administrative and commercial managers", OccupNameUkr = "Адміністративні та комерційні керівники", ParentOccupID = "1" });
            _AllCodes.Add(new ISCO() { OccupID = "13", OccupName = "Production and specialized services managers", OccupNameUkr = "Керівники виробництв та спеціалізованих послуг", ParentOccupID = "1" });
            _AllCodes.Add(new ISCO() { OccupID = "14", OccupName = "Hospitality, retail and other services managers", OccupNameUkr = "Керівники готельної, роздрібної торгівля та інших обслуговуючих галузей", ParentOccupID = "1" });
            _AllCodes.Add(new ISCO() { OccupID = "21", OccupName = "Science and engineering professionals", OccupNameUkr = "Наукові та інженерні фахівці", ParentOccupID = "2" });
            _AllCodes.Add(new ISCO() { OccupID = "22", OccupName = "Health professionals", OccupNameUkr = "Фахівці сфери охорони здоров'я", ParentOccupID = "2" });
            _AllCodes.Add(new ISCO() { OccupID = "23", OccupName = "Teaching professionals", OccupNameUkr = "Вчителі", ParentOccupID = "2" });
            _AllCodes.Add(new ISCO() { OccupID = "24", OccupName = "Business and administration professionals", OccupNameUkr = "Фахівці бізнесу та адміністрування", ParentOccupID = "2" });
            _AllCodes.Add(new ISCO() { OccupID = "25", OccupName = "Information and communications technology professionals", OccupNameUkr = "Фахівці сфери інформаційних та комунікаційних технологій", ParentOccupID = "2" });
            _AllCodes.Add(new ISCO() { OccupID = "26", OccupName = "Legal, social and cultural professionals", OccupNameUkr = "Юридичні, соціальні та культурні фахівці", ParentOccupID = "2" });
            _AllCodes.Add(new ISCO() { OccupID = "31", OccupName = "Science and engineering associate professionals", OccupNameUkr = "", ParentOccupID = "3" });
            _AllCodes.Add(new ISCO() { OccupID = "32", OccupName = "Health associate professionals", OccupNameUkr = "", ParentOccupID = "3" });
            _AllCodes.Add(new ISCO() { OccupID = "33", OccupName = "Business and administration associate professionals", OccupNameUkr = "", ParentOccupID = "3" });
            _AllCodes.Add(new ISCO() { OccupID = "34", OccupName = "Legal, social, cultural and related associate professionals", OccupNameUkr = "", ParentOccupID = "3" });
            _AllCodes.Add(new ISCO() { OccupID = "35", OccupName = "Information and communications technicians", OccupNameUkr = "", ParentOccupID = "3" });
            _AllCodes.Add(new ISCO() { OccupID = "41", OccupName = "General and keyboard clerks", OccupNameUkr = "", ParentOccupID = "4" });
            _AllCodes.Add(new ISCO() { OccupID = "42", OccupName = "Customer services clerks", OccupNameUkr = "", ParentOccupID = "4" });
            _AllCodes.Add(new ISCO() { OccupID = "43", OccupName = "Numerical and material recording clerks", OccupNameUkr = "", ParentOccupID = "4" });
            _AllCodes.Add(new ISCO() { OccupID = "44", OccupName = "Other clerical support workers", OccupNameUkr = "", ParentOccupID = "4" });
            _AllCodes.Add(new ISCO() { OccupID = "51", OccupName = "Personal service workers", OccupNameUkr = "", ParentOccupID = "5" });
            _AllCodes.Add(new ISCO() { OccupID = "52", OccupName = "Sales workers", OccupNameUkr = "", ParentOccupID = "5" });
            _AllCodes.Add(new ISCO() { OccupID = "53", OccupName = "Personal care workers", OccupNameUkr = "", ParentOccupID = "5" });
            _AllCodes.Add(new ISCO() { OccupID = "54", OccupName = "Protective services workers", OccupNameUkr = "", ParentOccupID = "5" });
            _AllCodes.Add(new ISCO() { OccupID = "61", OccupName = "Market-oriented skilled agricultural workers", OccupNameUkr = "", ParentOccupID = "6" });
            _AllCodes.Add(new ISCO() { OccupID = "62", OccupName = "Market-oriented skilled forestry, fishing and hunting workers", OccupNameUkr = "", ParentOccupID = "6" });
            _AllCodes.Add(new ISCO() { OccupID = "63", OccupName = "Subsistence farmers, fishers, hunters and gatherers", OccupNameUkr = "", ParentOccupID = "6" });
            _AllCodes.Add(new ISCO() { OccupID = "71", OccupName = "Building and related trades workers, excluding electricians", OccupNameUkr = "", ParentOccupID = "7" });
            _AllCodes.Add(new ISCO() { OccupID = "72", OccupName = "Metal, machinery and related trades workers", OccupNameUkr = "", ParentOccupID = "7" });
            _AllCodes.Add(new ISCO() { OccupID = "73", OccupName = "Handicraft and printing workers", OccupNameUkr = "", ParentOccupID = "7" });
            _AllCodes.Add(new ISCO() { OccupID = "74", OccupName = "Electrical and electronic trades workers", OccupNameUkr = "", ParentOccupID = "7" });
            _AllCodes.Add(new ISCO() { OccupID = "75", OccupName = "Food processing, wood working, garment and other craft and related trades", OccupNameUkr = "", ParentOccupID = "7" });
            _AllCodes.Add(new ISCO() { OccupID = "81", OccupName = "Stationary plant and machine operators", OccupNameUkr = "", ParentOccupID = "8" });
            _AllCodes.Add(new ISCO() { OccupID = "82", OccupName = "Assemblers", OccupNameUkr = "", ParentOccupID = "8" });
            _AllCodes.Add(new ISCO() { OccupID = "83", OccupName = "Drivers and mobile plant operators", OccupNameUkr = "", ParentOccupID = "8" });
            _AllCodes.Add(new ISCO() { OccupID = "91", OccupName = "Cleaners and helpers", OccupNameUkr = "", ParentOccupID = "9" });
            _AllCodes.Add(new ISCO() { OccupID = "92", OccupName = "Agricultural, forestry and fishery labourers", OccupNameUkr = "", ParentOccupID = "9" });
            _AllCodes.Add(new ISCO() { OccupID = "93", OccupName = "Labourers in mining, construction, manufacturing and transport", OccupNameUkr = "", ParentOccupID = "9" });
            _AllCodes.Add(new ISCO() { OccupID = "94", OccupName = "Food preparation assistants", OccupNameUkr = "", ParentOccupID = "9" });
            _AllCodes.Add(new ISCO() { OccupID = "95", OccupName = "Street and related sales and service workers", OccupNameUkr = "", ParentOccupID = "9" });
            _AllCodes.Add(new ISCO() { OccupID = "96", OccupName = "Refuse workers and other elementary workers", OccupNameUkr = "", ParentOccupID = "9" });
            _AllCodes.Add(new ISCO() { OccupID = "01", OccupName = "Commissioned armed forces officers", OccupNameUkr = "", ParentOccupID = "0" });
            _AllCodes.Add(new ISCO() { OccupID = "02", OccupName = "Non-commissioned armed forces officers", OccupNameUkr = "", ParentOccupID = "0" });
            _AllCodes.Add(new ISCO() { OccupID = "6", OccupName = "Resolution Concerning Updating ISCO", OccupNameUkr = "", ParentOccupID = "" });
            _AllCodes.Add(new ISCO() { OccupID = "111", OccupName = "Legislators and senior officials", OccupNameUkr = "", ParentOccupID = "11" });
            _AllCodes.Add(new ISCO() { OccupID = "112", OccupName = "Managing directors and chief executives", OccupNameUkr = "", ParentOccupID = "11" });
            _AllCodes.Add(new ISCO() { OccupID = "121", OccupName = "Business services and administration managers", OccupNameUkr = "", ParentOccupID = "12" });
            _AllCodes.Add(new ISCO() { OccupID = "122", OccupName = "Sales, marketing and development managers", OccupNameUkr = "", ParentOccupID = "12" });
            _AllCodes.Add(new ISCO() { OccupID = "131", OccupName = "Production managers in agriculture, forestry and fisheries", OccupNameUkr = "", ParentOccupID = "13" });
            _AllCodes.Add(new ISCO() { OccupID = "132", OccupName = "Manufacturing, mining, construction, and distribution managers", OccupNameUkr = "", ParentOccupID = "13" });
            _AllCodes.Add(new ISCO() { OccupID = "133", OccupName = "Information and communications technology service managers", OccupNameUkr = "", ParentOccupID = "13" });
            _AllCodes.Add(new ISCO() { OccupID = "134", OccupName = "Professional services managers", OccupNameUkr = "", ParentOccupID = "13" });
            _AllCodes.Add(new ISCO() { OccupID = "141", OccupName = "Hotel and restaurant managers", OccupNameUkr = "", ParentOccupID = "14" });
            _AllCodes.Add(new ISCO() { OccupID = "142", OccupName = "Retail and wholesale trade managers", OccupNameUkr = "", ParentOccupID = "14" });
            _AllCodes.Add(new ISCO() { OccupID = "143", OccupName = "Other services managers", OccupNameUkr = "", ParentOccupID = "14" });
            _AllCodes.Add(new ISCO() { OccupID = "211", OccupName = "Physical and earth science professionals", OccupNameUkr = "", ParentOccupID = "21" });
            _AllCodes.Add(new ISCO() { OccupID = "212", OccupName = "Mathematicians, actuaries and statisticians", OccupNameUkr = "", ParentOccupID = "21" });
            _AllCodes.Add(new ISCO() { OccupID = "213", OccupName = "Life science professionals", OccupNameUkr = "", ParentOccupID = "21" });
            _AllCodes.Add(new ISCO() { OccupID = "214", OccupName = "Engineering professionals (excluding electrotechnology)", OccupNameUkr = "", ParentOccupID = "21" });
            _AllCodes.Add(new ISCO() { OccupID = "215", OccupName = "Electrotechnology engineers", OccupNameUkr = "", ParentOccupID = "21" });
            _AllCodes.Add(new ISCO() { OccupID = "216", OccupName = "Architects, planners, surveyors and designers", OccupNameUkr = "", ParentOccupID = "21" });
            _AllCodes.Add(new ISCO() { OccupID = "221", OccupName = "Medical doctors", OccupNameUkr = "", ParentOccupID = "22" });
            _AllCodes.Add(new ISCO() { OccupID = "222", OccupName = "Nursing and midwifery professionals", OccupNameUkr = "", ParentOccupID = "22" });
            _AllCodes.Add(new ISCO() { OccupID = "223", OccupName = "Traditional and complementary medicine professionals", OccupNameUkr = "", ParentOccupID = "22" });
            _AllCodes.Add(new ISCO() { OccupID = "224", OccupName = "Paramedical practitioners", OccupNameUkr = "", ParentOccupID = "22" });
            _AllCodes.Add(new ISCO() { OccupID = "225", OccupName = "Veterinarians", OccupNameUkr = "", ParentOccupID = "22" });
            _AllCodes.Add(new ISCO() { OccupID = "226", OccupName = "Other health professionals", OccupNameUkr = "", ParentOccupID = "22" });
            _AllCodes.Add(new ISCO() { OccupID = "231", OccupName = "University and higher education teachers", OccupNameUkr = "", ParentOccupID = "23" });
            _AllCodes.Add(new ISCO() { OccupID = "232", OccupName = "Vocational education teachers", OccupNameUkr = "", ParentOccupID = "23" });
            _AllCodes.Add(new ISCO() { OccupID = "233", OccupName = "Secondary education teachers", OccupNameUkr = "", ParentOccupID = "23" });
            _AllCodes.Add(new ISCO() { OccupID = "234", OccupName = "Primary school and early childhood teachers", OccupNameUkr = "", ParentOccupID = "23" });
            _AllCodes.Add(new ISCO() { OccupID = "235", OccupName = "Other teaching professionals", OccupNameUkr = "", ParentOccupID = "23" });
            _AllCodes.Add(new ISCO() { OccupID = "241", OccupName = "Finance professionals", OccupNameUkr = "", ParentOccupID = "24" });
            _AllCodes.Add(new ISCO() { OccupID = "242", OccupName = "Administration professionals", OccupNameUkr = "", ParentOccupID = "24" });
            _AllCodes.Add(new ISCO() { OccupID = "243", OccupName = "Sales, marketing and public relations professionals", OccupNameUkr = "", ParentOccupID = "24" });
            _AllCodes.Add(new ISCO() { OccupID = "251", OccupName = "Software and applications developers and analysts", OccupNameUkr = "", ParentOccupID = "25" });
            _AllCodes.Add(new ISCO() { OccupID = "252", OccupName = "Database and network professionals", OccupNameUkr = "", ParentOccupID = "25" });
            _AllCodes.Add(new ISCO() { OccupID = "261", OccupName = "Legal professionals", OccupNameUkr = "", ParentOccupID = "26" });
            _AllCodes.Add(new ISCO() { OccupID = "262", OccupName = "Librarians, archivists and curators", OccupNameUkr = "", ParentOccupID = "26" });
            _AllCodes.Add(new ISCO() { OccupID = "263", OccupName = "Social and religious professionals", OccupNameUkr = "", ParentOccupID = "26" });
            _AllCodes.Add(new ISCO() { OccupID = "264", OccupName = "Authors, journalists and linguists", OccupNameUkr = "", ParentOccupID = "26" });
            _AllCodes.Add(new ISCO() { OccupID = "265", OccupName = "Creative and performing artists", OccupNameUkr = "", ParentOccupID = "26" });
            _AllCodes.Add(new ISCO() { OccupID = "311", OccupName = "Physical and engineering science technicians", OccupNameUkr = "", ParentOccupID = "31" });
            _AllCodes.Add(new ISCO() { OccupID = "312", OccupName = "Mining, manufacturing and construction supervisors", OccupNameUkr = "", ParentOccupID = "31" });
            _AllCodes.Add(new ISCO() { OccupID = "313", OccupName = "Process control technicians", OccupNameUkr = "", ParentOccupID = "31" });
            _AllCodes.Add(new ISCO() { OccupID = "314", OccupName = "Life science technicians and related associate professionals", OccupNameUkr = "", ParentOccupID = "31" });
            _AllCodes.Add(new ISCO() { OccupID = "315", OccupName = "Ship and aircraft controllers and technicians", OccupNameUkr = "", ParentOccupID = "31" });
            _AllCodes.Add(new ISCO() { OccupID = "321", OccupName = "Medical and pharmaceutical technicians", OccupNameUkr = "", ParentOccupID = "32" });
            _AllCodes.Add(new ISCO() { OccupID = "322", OccupName = "Nursing and midwifery associate professionals", OccupNameUkr = "", ParentOccupID = "32" });
            _AllCodes.Add(new ISCO() { OccupID = "323", OccupName = "Traditional and complementary medicine associate professionals", OccupNameUkr = "", ParentOccupID = "32" });
            _AllCodes.Add(new ISCO() { OccupID = "324", OccupName = "Veterinary technicians and assistants", OccupNameUkr = "", ParentOccupID = "32" });
            _AllCodes.Add(new ISCO() { OccupID = "325", OccupName = "Other health associate professionals", OccupNameUkr = "", ParentOccupID = "32" });
            _AllCodes.Add(new ISCO() { OccupID = "331", OccupName = "Financial and mathematical associate professionals", OccupNameUkr = "", ParentOccupID = "33" });
            _AllCodes.Add(new ISCO() { OccupID = "332", OccupName = "Sales and purchasing agents and brokers", OccupNameUkr = "", ParentOccupID = "33" });
            _AllCodes.Add(new ISCO() { OccupID = "333", OccupName = "Business services agents", OccupNameUkr = "", ParentOccupID = "33" });
            _AllCodes.Add(new ISCO() { OccupID = "334", OccupName = "Administrative and specialized secretaries", OccupNameUkr = "", ParentOccupID = "33" });
            _AllCodes.Add(new ISCO() { OccupID = "335", OccupName = "Regulatory government associate professionals", OccupNameUkr = "", ParentOccupID = "33" });
            _AllCodes.Add(new ISCO() { OccupID = "341", OccupName = "Legal, social and religious associate professionals", OccupNameUkr = "", ParentOccupID = "34" });
            _AllCodes.Add(new ISCO() { OccupID = "342", OccupName = "Sports and fitness workers", OccupNameUkr = "", ParentOccupID = "34" });
            _AllCodes.Add(new ISCO() { OccupID = "343", OccupName = "Artistic, cultural and culinary associate professionals", OccupNameUkr = "", ParentOccupID = "34" });
            _AllCodes.Add(new ISCO() { OccupID = "351", OccupName = "Information and communications technology operations and user support", OccupNameUkr = "", ParentOccupID = "35" });
            _AllCodes.Add(new ISCO() { OccupID = "352", OccupName = "Telecommunications and broadcasting technicians", OccupNameUkr = "", ParentOccupID = "35" });
            _AllCodes.Add(new ISCO() { OccupID = "411", OccupName = "General office clerks", OccupNameUkr = "", ParentOccupID = "41" });
            _AllCodes.Add(new ISCO() { OccupID = "412", OccupName = "Secretaries (general)", OccupNameUkr = "", ParentOccupID = "41" });
            _AllCodes.Add(new ISCO() { OccupID = "413", OccupName = "Keyboard operators", OccupNameUkr = "", ParentOccupID = "41" });
            _AllCodes.Add(new ISCO() { OccupID = "421", OccupName = "Tellers, money collectors and related clerks", OccupNameUkr = "", ParentOccupID = "42" });
            _AllCodes.Add(new ISCO() { OccupID = "422", OccupName = "Client information workers", OccupNameUkr = "", ParentOccupID = "42" });
            _AllCodes.Add(new ISCO() { OccupID = "431", OccupName = "Numerical clerks", OccupNameUkr = "", ParentOccupID = "43" });
            _AllCodes.Add(new ISCO() { OccupID = "432", OccupName = "Material-recording and transport clerks", OccupNameUkr = "", ParentOccupID = "43" });
            _AllCodes.Add(new ISCO() { OccupID = "441", OccupName = "Other clerical support workers", OccupNameUkr = "", ParentOccupID = "44" });
            _AllCodes.Add(new ISCO() { OccupID = "511", OccupName = "Travel attendants, conductors and guides", OccupNameUkr = "", ParentOccupID = "51" });
            _AllCodes.Add(new ISCO() { OccupID = "512", OccupName = "Cooks", OccupNameUkr = "", ParentOccupID = "51" });
            _AllCodes.Add(new ISCO() { OccupID = "513", OccupName = "Waiters and bartenders", OccupNameUkr = "", ParentOccupID = "51" });
            _AllCodes.Add(new ISCO() { OccupID = "514", OccupName = "Hairdressers, beauticians and related workers", OccupNameUkr = "", ParentOccupID = "51" });
            _AllCodes.Add(new ISCO() { OccupID = "515", OccupName = "Building and housekeeping supervisors", OccupNameUkr = "", ParentOccupID = "51" });
            _AllCodes.Add(new ISCO() { OccupID = "516", OccupName = "Other personal services workers", OccupNameUkr = "", ParentOccupID = "51" });
            _AllCodes.Add(new ISCO() { OccupID = "521", OccupName = "Street and market salespersons", OccupNameUkr = "", ParentOccupID = "52" });
            _AllCodes.Add(new ISCO() { OccupID = "522", OccupName = "Shop salespersons", OccupNameUkr = "", ParentOccupID = "52" });
            _AllCodes.Add(new ISCO() { OccupID = "523", OccupName = "Cashiers and ticket clerks", OccupNameUkr = "", ParentOccupID = "52" });
            _AllCodes.Add(new ISCO() { OccupID = "524", OccupName = "Other sales workers", OccupNameUkr = "", ParentOccupID = "52" });
            _AllCodes.Add(new ISCO() { OccupID = "531", OccupName = "Child care workers and teachers' aides", OccupNameUkr = "", ParentOccupID = "53" });
            _AllCodes.Add(new ISCO() { OccupID = "532", OccupName = "Personal care workers in health services", OccupNameUkr = "", ParentOccupID = "53" });
            _AllCodes.Add(new ISCO() { OccupID = "541", OccupName = "Protective services workers", OccupNameUkr = "", ParentOccupID = "54" });
            _AllCodes.Add(new ISCO() { OccupID = "611", OccupName = "Market gardeners and crop growers", OccupNameUkr = "", ParentOccupID = "61" });
            _AllCodes.Add(new ISCO() { OccupID = "612", OccupName = "Animal producers", OccupNameUkr = "", ParentOccupID = "61" });
            _AllCodes.Add(new ISCO() { OccupID = "613", OccupName = "Mixed crop and animal producers", OccupNameUkr = "", ParentOccupID = "61" });
            _AllCodes.Add(new ISCO() { OccupID = "10", OccupName = "Resolution Concerning Updating ISCO", OccupNameUkr = "", ParentOccupID = "1" });
            _AllCodes.Add(new ISCO() { OccupID = "621", OccupName = "Forestry and related workers", OccupNameUkr = "", ParentOccupID = "62" });
            _AllCodes.Add(new ISCO() { OccupID = "622", OccupName = "Fishery workers, hunters and trappers", OccupNameUkr = "", ParentOccupID = "62" });
            _AllCodes.Add(new ISCO() { OccupID = "631", OccupName = "Subsistence crop farmers", OccupNameUkr = "", ParentOccupID = "63" });
            _AllCodes.Add(new ISCO() { OccupID = "632", OccupName = "Subsistence livestock farmers", OccupNameUkr = "", ParentOccupID = "63" });
            _AllCodes.Add(new ISCO() { OccupID = "633", OccupName = "Subsistence mixed crop and livestock farmers", OccupNameUkr = "", ParentOccupID = "63" });
            _AllCodes.Add(new ISCO() { OccupID = "634", OccupName = "Subsistence fishers, hunters, trappers and gatherers", OccupNameUkr = "", ParentOccupID = "63" });
            _AllCodes.Add(new ISCO() { OccupID = "711", OccupName = "Building frame and related trades workers", OccupNameUkr = "", ParentOccupID = "71" });
            _AllCodes.Add(new ISCO() { OccupID = "712", OccupName = "Building finishers and related trades workers", OccupNameUkr = "", ParentOccupID = "71" });
            _AllCodes.Add(new ISCO() { OccupID = "713", OccupName = "Painters, building structure cleaners and related trades workers", OccupNameUkr = "", ParentOccupID = "71" });
            _AllCodes.Add(new ISCO() { OccupID = "721", OccupName = "Sheet and structural metal workers, moulders and welders, and related", OccupNameUkr = "", ParentOccupID = "72" });
            _AllCodes.Add(new ISCO() { OccupID = "722", OccupName = "Blacksmiths, toolmakers and related trades workers", OccupNameUkr = "", ParentOccupID = "72" });
            _AllCodes.Add(new ISCO() { OccupID = "723", OccupName = "Machinery mechanics and repairers", OccupNameUkr = "", ParentOccupID = "72" });
            _AllCodes.Add(new ISCO() { OccupID = "731", OccupName = "Handicraft workers", OccupNameUkr = "", ParentOccupID = "73" });
            _AllCodes.Add(new ISCO() { OccupID = "732", OccupName = "Printing trades workers", OccupNameUkr = "", ParentOccupID = "73" });
            _AllCodes.Add(new ISCO() { OccupID = "741", OccupName = "Electrical equipment installers and repairers", OccupNameUkr = "", ParentOccupID = "74" });
            _AllCodes.Add(new ISCO() { OccupID = "742", OccupName = "Electronics and telecommunications installers and repairers", OccupNameUkr = "", ParentOccupID = "74" });
            _AllCodes.Add(new ISCO() { OccupID = "75", OccupName = "Food processing, wood working, garment and other craft and related trades", OccupNameUkr = "", ParentOccupID = "7" });
            _AllCodes.Add(new ISCO() { OccupID = "751", OccupName = "Food processing and related trades workers", OccupNameUkr = "", ParentOccupID = "75" });
            _AllCodes.Add(new ISCO() { OccupID = "752", OccupName = "Wood treaters, cabinet-makers and related trades workers", OccupNameUkr = "", ParentOccupID = "75" });
            _AllCodes.Add(new ISCO() { OccupID = "753", OccupName = "Garment and related trades workers", OccupNameUkr = "", ParentOccupID = "75" });
            _AllCodes.Add(new ISCO() { OccupID = "754", OccupName = "Other craft and related workers", OccupNameUkr = "", ParentOccupID = "75" });
            _AllCodes.Add(new ISCO() { OccupID = "811", OccupName = "Mining and mineral processing plant operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "812", OccupName = "Metal processing and finishing plant operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "813", OccupName = "Chemical and photographic products plant and machine operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "814", OccupName = "Rubber, plastic and paper products machine operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "815", OccupName = "Textile, fur and leather products machine operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "816", OccupName = "Food and related products machine operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "817", OccupName = "Wood processing and papermaking plant operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "818", OccupName = "Other stationary plant and machine operators", OccupNameUkr = "", ParentOccupID = "81" });
            _AllCodes.Add(new ISCO() { OccupID = "821", OccupName = "Assemblers", OccupNameUkr = "", ParentOccupID = "82" });
            _AllCodes.Add(new ISCO() { OccupID = "831", OccupName = "Locomotive engine drivers and related workers", OccupNameUkr = "", ParentOccupID = "83" });
            _AllCodes.Add(new ISCO() { OccupID = "832", OccupName = "Car, van and motorcycle drivers", OccupNameUkr = "", ParentOccupID = "83" });
            _AllCodes.Add(new ISCO() { OccupID = "833", OccupName = "Heavy truck and bus drivers", OccupNameUkr = "", ParentOccupID = "83" });
            _AllCodes.Add(new ISCO() { OccupID = "834", OccupName = "Mobile plant operators", OccupNameUkr = "", ParentOccupID = "83" });
            _AllCodes.Add(new ISCO() { OccupID = "835", OccupName = "Ships' deck crews and related workers", OccupNameUkr = "", ParentOccupID = "83" });
            _AllCodes.Add(new ISCO() { OccupID = "911", OccupName = "Domestic, hotel and office cleaners and helpers", OccupNameUkr = "", ParentOccupID = "91" });
            _AllCodes.Add(new ISCO() { OccupID = "912", OccupName = "Vehicle, window, laundry and other hand cleaning workers", OccupNameUkr = "", ParentOccupID = "91" });
            _AllCodes.Add(new ISCO() { OccupID = "921", OccupName = "Agricultural, forestry and fishery labourers", OccupNameUkr = "", ParentOccupID = "92" });
            _AllCodes.Add(new ISCO() { OccupID = "931", OccupName = "Mining and construction labourers", OccupNameUkr = "", ParentOccupID = "93" });
            _AllCodes.Add(new ISCO() { OccupID = "932", OccupName = "Manufacturing labourers", OccupNameUkr = "", ParentOccupID = "93" });
            _AllCodes.Add(new ISCO() { OccupID = "933", OccupName = "Transport and storage labourers", OccupNameUkr = "", ParentOccupID = "93" });
            _AllCodes.Add(new ISCO() { OccupID = "12", OccupName = "Resolution Concerning Updating ISCO", OccupNameUkr = "", ParentOccupID = "1" });
            _AllCodes.Add(new ISCO() { OccupID = "941", OccupName = "Food preparation assistants", OccupNameUkr = "", ParentOccupID = "94" });
            _AllCodes.Add(new ISCO() { OccupID = "951", OccupName = "Street and related service workers", OccupNameUkr = "", ParentOccupID = "95" });
            _AllCodes.Add(new ISCO() { OccupID = "952", OccupName = "Street vendors (excluding food)", OccupNameUkr = "", ParentOccupID = "95" });
            _AllCodes.Add(new ISCO() { OccupID = "961", OccupName = "Refuse workers", OccupNameUkr = "", ParentOccupID = "96" });
            _AllCodes.Add(new ISCO() { OccupID = "962", OccupName = "Other elementary workers", OccupNameUkr = "", ParentOccupID = "96" });
            _AllCodes.Add(new ISCO() { OccupID = "011", OccupName = "Commissioned armed forces officers", OccupNameUkr = "", ParentOccupID = "01" });
            _AllCodes.Add(new ISCO() { OccupID = "021", OccupName = "Non-commissioned armed forces officers", OccupNameUkr = "", ParentOccupID = "02" });
            _AllCodes.Add(new ISCO() { OccupID = "031", OccupName = "Armed forces occupations, other ranks", OccupNameUkr = "", ParentOccupID = "03" });
            _AllCodes.Add(new ISCO() { OccupID = "1111", OccupName = "Legislators", OccupNameUkr = "", ParentOccupID = "111" });
            _AllCodes.Add(new ISCO() { OccupID = "1112", OccupName = "Senior government officials", OccupNameUkr = "", ParentOccupID = "111" });
            _AllCodes.Add(new ISCO() { OccupID = "1113", OccupName = "Traditional chiefs and heads of village", OccupNameUkr = "", ParentOccupID = "111" });
            _AllCodes.Add(new ISCO() { OccupID = "1114", OccupName = "Senior officials of special-interest organizations", OccupNameUkr = "", ParentOccupID = "111" });
            _AllCodes.Add(new ISCO() { OccupID = "1120", OccupName = "Managing directors and chief executives", OccupNameUkr = "", ParentOccupID = "112" });
            _AllCodes.Add(new ISCO() { OccupID = "1211", OccupName = "Finance managers", OccupNameUkr = "", ParentOccupID = "121" });
            _AllCodes.Add(new ISCO() { OccupID = "1212", OccupName = "Human resource managers", OccupNameUkr = "", ParentOccupID = "121" });
            _AllCodes.Add(new ISCO() { OccupID = "1213", OccupName = "Policy and planning managers", OccupNameUkr = "", ParentOccupID = "121" });
            _AllCodes.Add(new ISCO() { OccupID = "1219", OccupName = "Business services and administration managers not elsewhere", OccupNameUkr = "", ParentOccupID = "121" });
            _AllCodes.Add(new ISCO() { OccupID = "1221", OccupName = "Sales and marketing managers", OccupNameUkr = "", ParentOccupID = "122" });
            _AllCodes.Add(new ISCO() { OccupID = "1222", OccupName = "Advertising and public relations managers", OccupNameUkr = "", ParentOccupID = "122" });
            _AllCodes.Add(new ISCO() { OccupID = "1223", OccupName = "Research and development managers", OccupNameUkr = "", ParentOccupID = "122" });
            _AllCodes.Add(new ISCO() { OccupID = "1311", OccupName = "Agricultural and forestry production managers", OccupNameUkr = "", ParentOccupID = "131" });
            _AllCodes.Add(new ISCO() { OccupID = "1312", OccupName = "Aquaculture and fisheries production managers", OccupNameUkr = "", ParentOccupID = "131" });
            _AllCodes.Add(new ISCO() { OccupID = "1321", OccupName = "Manufacturing managers", OccupNameUkr = "", ParentOccupID = "132" });
            _AllCodes.Add(new ISCO() { OccupID = "1322", OccupName = "Mining managers", OccupNameUkr = "", ParentOccupID = "132" });
            _AllCodes.Add(new ISCO() { OccupID = "1323", OccupName = "Construction managers", OccupNameUkr = "", ParentOccupID = "132" });
            _AllCodes.Add(new ISCO() { OccupID = "1324", OccupName = "Supply, distribution and related managers", OccupNameUkr = "", ParentOccupID = "132" });
            _AllCodes.Add(new ISCO() { OccupID = "1330", OccupName = "Information and communications technology service managers", OccupNameUkr = "", ParentOccupID = "133" });
            _AllCodes.Add(new ISCO() { OccupID = "1341", OccupName = "Child care services managers", OccupNameUkr = "", ParentOccupID = "134" });
            _AllCodes.Add(new ISCO() { OccupID = "1342", OccupName = "Health services managers", OccupNameUkr = "", ParentOccupID = "134" });
            _AllCodes.Add(new ISCO() { OccupID = "1343", OccupName = "Aged care services managers", OccupNameUkr = "", ParentOccupID = "134" });
            _AllCodes.Add(new ISCO() { OccupID = "1344", OccupName = "Social welfare managers", OccupNameUkr = "", ParentOccupID = "134" });
            _AllCodes.Add(new ISCO() { OccupID = "1345", OccupName = "Education managers", OccupNameUkr = "", ParentOccupID = "134" });
            _AllCodes.Add(new ISCO() { OccupID = "1346", OccupName = "Financial and insurance services branch managers", OccupNameUkr = "", ParentOccupID = "134" });
            _AllCodes.Add(new ISCO() { OccupID = "1349", OccupName = "Professional services managers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "134" });
            _AllCodes.Add(new ISCO() { OccupID = "1411", OccupName = "Hotel managers", OccupNameUkr = "", ParentOccupID = "141" });
            _AllCodes.Add(new ISCO() { OccupID = "1412", OccupName = "Restaurant managers", OccupNameUkr = "", ParentOccupID = "141" });
            _AllCodes.Add(new ISCO() { OccupID = "1420", OccupName = "Retail and wholesale trade managers", OccupNameUkr = "", ParentOccupID = "142" });
            _AllCodes.Add(new ISCO() { OccupID = "1431", OccupName = "Sports, recreation and cultural centre managers", OccupNameUkr = "", ParentOccupID = "143" });
            _AllCodes.Add(new ISCO() { OccupID = "1439", OccupName = "Services managers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "143" });
            _AllCodes.Add(new ISCO() { OccupID = "2111", OccupName = "Physicists and astronomers", OccupNameUkr = "", ParentOccupID = "211" });
            _AllCodes.Add(new ISCO() { OccupID = "2112", OccupName = "Meteorologists", OccupNameUkr = "", ParentOccupID = "211" });
            _AllCodes.Add(new ISCO() { OccupID = "2113", OccupName = "Chemists", OccupNameUkr = "", ParentOccupID = "211" });
            _AllCodes.Add(new ISCO() { OccupID = "2114", OccupName = "Geologists and geophysicists", OccupNameUkr = "", ParentOccupID = "211" });
            _AllCodes.Add(new ISCO() { OccupID = "2120", OccupName = "Mathematicians, actuaries and statisticians", OccupNameUkr = "", ParentOccupID = "212" });
            _AllCodes.Add(new ISCO() { OccupID = "2131", OccupName = "Biologists, botanists, zoologists and related professionals", OccupNameUkr = "", ParentOccupID = "213" });
            _AllCodes.Add(new ISCO() { OccupID = "2132", OccupName = "Farming, forestry and fisheries advisers", OccupNameUkr = "", ParentOccupID = "213" });
            _AllCodes.Add(new ISCO() { OccupID = "2133", OccupName = "Environmental protection professionals", OccupNameUkr = "", ParentOccupID = "213" });
            _AllCodes.Add(new ISCO() { OccupID = "2141", OccupName = "Industrial and production engineers", OccupNameUkr = "", ParentOccupID = "214" });
            _AllCodes.Add(new ISCO() { OccupID = "2142", OccupName = "Civil engineers", OccupNameUkr = "", ParentOccupID = "214" });
            _AllCodes.Add(new ISCO() { OccupID = "2143", OccupName = "Environmental engineers", OccupNameUkr = "", ParentOccupID = "214" });
            _AllCodes.Add(new ISCO() { OccupID = "2144", OccupName = "Mechanical engineers", OccupNameUkr = "", ParentOccupID = "214" });
            _AllCodes.Add(new ISCO() { OccupID = "2145", OccupName = "Chemical engineers", OccupNameUkr = "", ParentOccupID = "214" });
            _AllCodes.Add(new ISCO() { OccupID = "2146", OccupName = "Mining engineers, metallurgists and related professionals", OccupNameUkr = "", ParentOccupID = "214" });
            _AllCodes.Add(new ISCO() { OccupID = "2149", OccupName = "Engineering professionals not elsewhere classified", OccupNameUkr = "", ParentOccupID = "214" });
            _AllCodes.Add(new ISCO() { OccupID = "2151", OccupName = "Electrical engineers", OccupNameUkr = "", ParentOccupID = "215" });
            _AllCodes.Add(new ISCO() { OccupID = "2152", OccupName = "Electronics engineers", OccupNameUkr = "", ParentOccupID = "215" });
            _AllCodes.Add(new ISCO() { OccupID = "2153", OccupName = "Telecommunications engineers", OccupNameUkr = "", ParentOccupID = "215" });
            _AllCodes.Add(new ISCO() { OccupID = "2161", OccupName = "Building architects", OccupNameUkr = "", ParentOccupID = "216" });
            _AllCodes.Add(new ISCO() { OccupID = "2162", OccupName = "Landscape architects", OccupNameUkr = "", ParentOccupID = "216" });
            _AllCodes.Add(new ISCO() { OccupID = "2163", OccupName = "Product and garment designers", OccupNameUkr = "", ParentOccupID = "216" });
            _AllCodes.Add(new ISCO() { OccupID = "2164", OccupName = "Town and traffic planners", OccupNameUkr = "", ParentOccupID = "216" });
            _AllCodes.Add(new ISCO() { OccupID = "2165", OccupName = "Cartographers and surveyors", OccupNameUkr = "", ParentOccupID = "216" });
            _AllCodes.Add(new ISCO() { OccupID = "2166", OccupName = "Graphic and multimedia designers", OccupNameUkr = "", ParentOccupID = "216" });
            _AllCodes.Add(new ISCO() { OccupID = "2211", OccupName = "Generalist medical practitioners", OccupNameUkr = "", ParentOccupID = "221" });
            _AllCodes.Add(new ISCO() { OccupID = "2212", OccupName = "Specialist medical practitioners", OccupNameUkr = "", ParentOccupID = "221" });
            _AllCodes.Add(new ISCO() { OccupID = "2221", OccupName = "Nursing professionals", OccupNameUkr = "", ParentOccupID = "222" });
            _AllCodes.Add(new ISCO() { OccupID = "2222", OccupName = "Midwifery professionals", OccupNameUkr = "", ParentOccupID = "222" });
            _AllCodes.Add(new ISCO() { OccupID = "2230", OccupName = "Traditional and complementary medicine professionals", OccupNameUkr = "", ParentOccupID = "223" });
            _AllCodes.Add(new ISCO() { OccupID = "2240", OccupName = "Paramedical practitioners", OccupNameUkr = "", ParentOccupID = "224" });
            _AllCodes.Add(new ISCO() { OccupID = "2250", OccupName = "Veterinarians", OccupNameUkr = "", ParentOccupID = "225" });
            _AllCodes.Add(new ISCO() { OccupID = "2261", OccupName = "Dentists", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2262", OccupName = "Pharmacists", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2263", OccupName = "Environmental and occupational health and hygiene professionals", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2264", OccupName = "Physiotherapists", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2265", OccupName = "Dieticians and nutritionists", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2266", OccupName = "Audiologists and speech therapists", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2267", OccupName = "Optometrists and ophthalmic opticians", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2269", OccupName = "Health professionals not elsewhere classified", OccupNameUkr = "", ParentOccupID = "226" });
            _AllCodes.Add(new ISCO() { OccupID = "2310", OccupName = "University and higher education teachers", OccupNameUkr = "", ParentOccupID = "231" });
            _AllCodes.Add(new ISCO() { OccupID = "2320", OccupName = "Vocational education teachers", OccupNameUkr = "", ParentOccupID = "232" });
            _AllCodes.Add(new ISCO() { OccupID = "2330", OccupName = "Secondary education teachers", OccupNameUkr = "", ParentOccupID = "233" });
            _AllCodes.Add(new ISCO() { OccupID = "2341", OccupName = "Primary school teachers", OccupNameUkr = "", ParentOccupID = "234" });
            _AllCodes.Add(new ISCO() { OccupID = "2342", OccupName = "Early childhood educators", OccupNameUkr = "", ParentOccupID = "234" });
            _AllCodes.Add(new ISCO() { OccupID = "2351", OccupName = "Education methods specialists", OccupNameUkr = "", ParentOccupID = "235" });
            _AllCodes.Add(new ISCO() { OccupID = "2352", OccupName = "Special needs teachers", OccupNameUkr = "", ParentOccupID = "235" });
            _AllCodes.Add(new ISCO() { OccupID = "2353", OccupName = "Other language teachers", OccupNameUkr = "", ParentOccupID = "235" });
            _AllCodes.Add(new ISCO() { OccupID = "2354", OccupName = "Other music teachers", OccupNameUkr = "", ParentOccupID = "235" });
            _AllCodes.Add(new ISCO() { OccupID = "2355", OccupName = "Other arts teachers", OccupNameUkr = "", ParentOccupID = "235" });
            _AllCodes.Add(new ISCO() { OccupID = "2356", OccupName = "Information technology trainers", OccupNameUkr = "", ParentOccupID = "235" });
            _AllCodes.Add(new ISCO() { OccupID = "2359", OccupName = "Teaching professionals not elsewhere classified", OccupNameUkr = "", ParentOccupID = "235" });
            _AllCodes.Add(new ISCO() { OccupID = "2411", OccupName = "Accountants", OccupNameUkr = "", ParentOccupID = "241" });
            _AllCodes.Add(new ISCO() { OccupID = "2412", OccupName = "Financial and investment advisers", OccupNameUkr = "", ParentOccupID = "241" });
            _AllCodes.Add(new ISCO() { OccupID = "2413", OccupName = "Financial analysts", OccupNameUkr = "", ParentOccupID = "241" });
            _AllCodes.Add(new ISCO() { OccupID = "2421", OccupName = "Management and organization analysts", OccupNameUkr = "", ParentOccupID = "242" });
            _AllCodes.Add(new ISCO() { OccupID = "2422", OccupName = "Policy administration professionals", OccupNameUkr = "", ParentOccupID = "242" });
            _AllCodes.Add(new ISCO() { OccupID = "2423", OccupName = "Personnel and careers professionals", OccupNameUkr = "", ParentOccupID = "242" });
            _AllCodes.Add(new ISCO() { OccupID = "2424", OccupName = "Training and staff development professionals", OccupNameUkr = "", ParentOccupID = "242" });
            _AllCodes.Add(new ISCO() { OccupID = "2431", OccupName = "Advertising and marketing professionals", OccupNameUkr = "", ParentOccupID = "243" });
            _AllCodes.Add(new ISCO() { OccupID = "2432", OccupName = "Public relations professionals", OccupNameUkr = "", ParentOccupID = "243" });
            _AllCodes.Add(new ISCO() { OccupID = "2433", OccupName = "Technical and medical sales professionals (excluding ICT)", OccupNameUkr = "", ParentOccupID = "243" });
            _AllCodes.Add(new ISCO() { OccupID = "2434", OccupName = "Information and communications technology sales professionals", OccupNameUkr = "", ParentOccupID = "243" });
            _AllCodes.Add(new ISCO() { OccupID = "2511", OccupName = "Systems analysts", OccupNameUkr = "", ParentOccupID = "251" });
            _AllCodes.Add(new ISCO() { OccupID = "2512", OccupName = "Software developers", OccupNameUkr = "", ParentOccupID = "251" });
            _AllCodes.Add(new ISCO() { OccupID = "2513", OccupName = "Web and multimedia developers", OccupNameUkr = "", ParentOccupID = "251" });
            _AllCodes.Add(new ISCO() { OccupID = "2514", OccupName = "Applications programmers", OccupNameUkr = "", ParentOccupID = "251" });
            _AllCodes.Add(new ISCO() { OccupID = "2519", OccupName = "Software and applications developers and analysts not elsewhere", OccupNameUkr = "", ParentOccupID = "251" });
            _AllCodes.Add(new ISCO() { OccupID = "2521", OccupName = "Database designers and administrators", OccupNameUkr = "", ParentOccupID = "252" });
            _AllCodes.Add(new ISCO() { OccupID = "2522", OccupName = "Systems administrators", OccupNameUkr = "", ParentOccupID = "252" });
            _AllCodes.Add(new ISCO() { OccupID = "2523", OccupName = "Computer network professionals", OccupNameUkr = "", ParentOccupID = "252" });
            _AllCodes.Add(new ISCO() { OccupID = "2529", OccupName = "Database and network professionals not elsewhere classified", OccupNameUkr = "", ParentOccupID = "252" });
            _AllCodes.Add(new ISCO() { OccupID = "2611", OccupName = "Lawyers", OccupNameUkr = "", ParentOccupID = "261" });
            _AllCodes.Add(new ISCO() { OccupID = "2612", OccupName = "Judges", OccupNameUkr = "", ParentOccupID = "261" });
            _AllCodes.Add(new ISCO() { OccupID = "2619", OccupName = "Legal professionals not elsewhere classified", OccupNameUkr = "", ParentOccupID = "261" });
            _AllCodes.Add(new ISCO() { OccupID = "2621", OccupName = "Archivists and curators", OccupNameUkr = "", ParentOccupID = "262" });
            _AllCodes.Add(new ISCO() { OccupID = "2622", OccupName = "Librarians and related information professionals", OccupNameUkr = "", ParentOccupID = "262" });
            _AllCodes.Add(new ISCO() { OccupID = "2631", OccupName = "Economists", OccupNameUkr = "", ParentOccupID = "263" });
            _AllCodes.Add(new ISCO() { OccupID = "2632", OccupName = "Sociologists, anthropologists and related professionals", OccupNameUkr = "", ParentOccupID = "263" });
            _AllCodes.Add(new ISCO() { OccupID = "2633", OccupName = "Philosophers, historians and political scientists", OccupNameUkr = "", ParentOccupID = "263" });
            _AllCodes.Add(new ISCO() { OccupID = "2634", OccupName = "Psychologists", OccupNameUkr = "", ParentOccupID = "263" });
            _AllCodes.Add(new ISCO() { OccupID = "2635", OccupName = "Social work and counselling professionals", OccupNameUkr = "", ParentOccupID = "263" });
            _AllCodes.Add(new ISCO() { OccupID = "2636", OccupName = "Religious professionals", OccupNameUkr = "", ParentOccupID = "263" });
            _AllCodes.Add(new ISCO() { OccupID = "2641", OccupName = "Authors and related writers", OccupNameUkr = "", ParentOccupID = "264" });
            _AllCodes.Add(new ISCO() { OccupID = "2642", OccupName = "Journalists", OccupNameUkr = "", ParentOccupID = "264" });
            _AllCodes.Add(new ISCO() { OccupID = "2643", OccupName = "Translators, interpreters and other linguists", OccupNameUkr = "", ParentOccupID = "264" });
            _AllCodes.Add(new ISCO() { OccupID = "2651", OccupName = "Visual artists", OccupNameUkr = "", ParentOccupID = "265" });
            _AllCodes.Add(new ISCO() { OccupID = "2652", OccupName = "Musicians, singers and composers", OccupNameUkr = "", ParentOccupID = "265" });
            _AllCodes.Add(new ISCO() { OccupID = "2653", OccupName = "Dancers and choreographers", OccupNameUkr = "", ParentOccupID = "265" });
            _AllCodes.Add(new ISCO() { OccupID = "2654", OccupName = "Film, stage and related directors and producers", OccupNameUkr = "", ParentOccupID = "265" });
            _AllCodes.Add(new ISCO() { OccupID = "2655", OccupName = "Actors", OccupNameUkr = "", ParentOccupID = "265" });
            _AllCodes.Add(new ISCO() { OccupID = "2656", OccupName = "Announcers on radio, television and other media", OccupNameUkr = "", ParentOccupID = "265" });
            _AllCodes.Add(new ISCO() { OccupID = "2659", OccupName = "Creative and performing artists not elsewhere classified", OccupNameUkr = "", ParentOccupID = "265" });
            _AllCodes.Add(new ISCO() { OccupID = "3111", OccupName = "Chemical and physical science technicians", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3112", OccupName = "Civil engineering technicians", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3113", OccupName = "Electrical engineering technicians", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3114", OccupName = "Electronics engineering technicians", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3115", OccupName = "Mechanical engineering technicians", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3116", OccupName = "Chemical engineering technicians", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3117", OccupName = "Mining and metallurgical technicians", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3118", OccupName = "Draughtspersons", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3119", OccupName = "Physical and engineering science technicians not elsewhere", OccupNameUkr = "", ParentOccupID = "311" });
            _AllCodes.Add(new ISCO() { OccupID = "3121", OccupName = "Mining supervisors", OccupNameUkr = "", ParentOccupID = "312" });
            _AllCodes.Add(new ISCO() { OccupID = "3122", OccupName = "Manufacturing supervisors", OccupNameUkr = "", ParentOccupID = "312" });
            _AllCodes.Add(new ISCO() { OccupID = "3123", OccupName = "Construction supervisors", OccupNameUkr = "", ParentOccupID = "312" });
            _AllCodes.Add(new ISCO() { OccupID = "3131", OccupName = "Power production plant operators", OccupNameUkr = "", ParentOccupID = "313" });
            _AllCodes.Add(new ISCO() { OccupID = "3132", OccupName = "Incinerator and water treatment plant operators", OccupNameUkr = "", ParentOccupID = "313" });
            _AllCodes.Add(new ISCO() { OccupID = "3133", OccupName = "Chemical processing plant controllers", OccupNameUkr = "", ParentOccupID = "313" });
            _AllCodes.Add(new ISCO() { OccupID = "3134", OccupName = "Petroleum and natural gas refining plant operators", OccupNameUkr = "", ParentOccupID = "313" });
            _AllCodes.Add(new ISCO() { OccupID = "3135", OccupName = "Metal production process controllers", OccupNameUkr = "", ParentOccupID = "313" });
            _AllCodes.Add(new ISCO() { OccupID = "3139", OccupName = "Process control technicians not elsewhere classified", OccupNameUkr = "", ParentOccupID = "313" });
            _AllCodes.Add(new ISCO() { OccupID = "3141", OccupName = "Life science technicians (excluding medical)", OccupNameUkr = "", ParentOccupID = "314" });
            _AllCodes.Add(new ISCO() { OccupID = "3142", OccupName = "Agricultural technicians", OccupNameUkr = "", ParentOccupID = "314" });
            _AllCodes.Add(new ISCO() { OccupID = "3143", OccupName = "Forestry technicians", OccupNameUkr = "", ParentOccupID = "314" });
            _AllCodes.Add(new ISCO() { OccupID = "3151", OccupName = "Ships' engineers", OccupNameUkr = "", ParentOccupID = "315" });
            _AllCodes.Add(new ISCO() { OccupID = "3152", OccupName = "Ships' deck officers and pilots", OccupNameUkr = "", ParentOccupID = "315" });
            _AllCodes.Add(new ISCO() { OccupID = "3153", OccupName = "Aircraft pilots and related associate professionals", OccupNameUkr = "", ParentOccupID = "315" });
            _AllCodes.Add(new ISCO() { OccupID = "3154", OccupName = "Air traffic controllers", OccupNameUkr = "", ParentOccupID = "315" });
            _AllCodes.Add(new ISCO() { OccupID = "3155", OccupName = "Air traffic safety electronics technicians", OccupNameUkr = "", ParentOccupID = "315" });
            _AllCodes.Add(new ISCO() { OccupID = "3211", OccupName = "Medical imaging and therapeutic equipment technicians", OccupNameUkr = "", ParentOccupID = "321" });
            _AllCodes.Add(new ISCO() { OccupID = "3212", OccupName = "Medical and pathology laboratory technicians", OccupNameUkr = "", ParentOccupID = "321" });
            _AllCodes.Add(new ISCO() { OccupID = "3213", OccupName = "Pharmaceutical technicians and assistants", OccupNameUkr = "", ParentOccupID = "321" });
            _AllCodes.Add(new ISCO() { OccupID = "3214", OccupName = "Medical and dental prosthetic technicians", OccupNameUkr = "", ParentOccupID = "321" });
            _AllCodes.Add(new ISCO() { OccupID = "3221", OccupName = "Nursing associate professionals", OccupNameUkr = "", ParentOccupID = "322" });
            _AllCodes.Add(new ISCO() { OccupID = "3222", OccupName = "Midwifery associate professionals", OccupNameUkr = "", ParentOccupID = "322" });
            _AllCodes.Add(new ISCO() { OccupID = "3230", OccupName = "Traditional and complementary medicine associate professionals", OccupNameUkr = "", ParentOccupID = "323" });
            _AllCodes.Add(new ISCO() { OccupID = "3240", OccupName = "Veterinary technicians and assistants", OccupNameUkr = "", ParentOccupID = "324" });
            _AllCodes.Add(new ISCO() { OccupID = "3251", OccupName = "Dental assistants and therapists", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3252", OccupName = "Medical records and health information technicians", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3253", OccupName = "Community health workers", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3254", OccupName = "Dispensing opticians", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3255", OccupName = "Physiotherapy technicians and assistants", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3256", OccupName = "Medical assistants", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3257", OccupName = "Environmental and occupational health inspectors and associates", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3258", OccupName = "Ambulance workers", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3259", OccupName = "Health associate professionals not elsewhere classified", OccupNameUkr = "", ParentOccupID = "325" });
            _AllCodes.Add(new ISCO() { OccupID = "3311", OccupName = "Securities and finance dealers and brokers", OccupNameUkr = "", ParentOccupID = "331" });
            _AllCodes.Add(new ISCO() { OccupID = "3312", OccupName = "Credit and loans officers", OccupNameUkr = "", ParentOccupID = "331" });
            _AllCodes.Add(new ISCO() { OccupID = "3313", OccupName = "Accounting associate professionals", OccupNameUkr = "", ParentOccupID = "331" });
            _AllCodes.Add(new ISCO() { OccupID = "3314", OccupName = "Statistical, mathematical and related associate professionals", OccupNameUkr = "", ParentOccupID = "331" });
            _AllCodes.Add(new ISCO() { OccupID = "3315", OccupName = "Valuers and loss assessors", OccupNameUkr = "", ParentOccupID = "331" });
            _AllCodes.Add(new ISCO() { OccupID = "3321", OccupName = "Insurance representatives", OccupNameUkr = "", ParentOccupID = "332" });
            _AllCodes.Add(new ISCO() { OccupID = "3322", OccupName = "Commercial sales representatives", OccupNameUkr = "", ParentOccupID = "332" });
            _AllCodes.Add(new ISCO() { OccupID = "3323", OccupName = "Buyers", OccupNameUkr = "", ParentOccupID = "332" });
            _AllCodes.Add(new ISCO() { OccupID = "3324", OccupName = "Trade brokers", OccupNameUkr = "", ParentOccupID = "332" });
            _AllCodes.Add(new ISCO() { OccupID = "3331", OccupName = "Clearing and forwarding agents", OccupNameUkr = "", ParentOccupID = "333" });
            _AllCodes.Add(new ISCO() { OccupID = "3332", OccupName = "Conference and event planners", OccupNameUkr = "", ParentOccupID = "333" });
            _AllCodes.Add(new ISCO() { OccupID = "3333", OccupName = "Employment agents and contractors", OccupNameUkr = "", ParentOccupID = "333" });
            _AllCodes.Add(new ISCO() { OccupID = "3334", OccupName = "Real estate agents and property managers", OccupNameUkr = "", ParentOccupID = "333" });
            _AllCodes.Add(new ISCO() { OccupID = "3339", OccupName = "Business services agents not elsewhere classified", OccupNameUkr = "", ParentOccupID = "333" });
            _AllCodes.Add(new ISCO() { OccupID = "3341", OccupName = "Office supervisors", OccupNameUkr = "", ParentOccupID = "334" });
            _AllCodes.Add(new ISCO() { OccupID = "3342", OccupName = "Legal secretaries", OccupNameUkr = "", ParentOccupID = "334" });
            _AllCodes.Add(new ISCO() { OccupID = "3343", OccupName = "Administrative and executive secretaries", OccupNameUkr = "", ParentOccupID = "334" });
            _AllCodes.Add(new ISCO() { OccupID = "3344", OccupName = "Medical secretaries", OccupNameUkr = "", ParentOccupID = "334" });
            _AllCodes.Add(new ISCO() { OccupID = "3351", OccupName = "Customs and border inspectors", OccupNameUkr = "", ParentOccupID = "335" });
            _AllCodes.Add(new ISCO() { OccupID = "3352", OccupName = "Government tax and excise officials", OccupNameUkr = "", ParentOccupID = "335" });
            _AllCodes.Add(new ISCO() { OccupID = "3353", OccupName = "Government social benefits officials", OccupNameUkr = "", ParentOccupID = "335" });
            _AllCodes.Add(new ISCO() { OccupID = "3354", OccupName = "Government licensing officials", OccupNameUkr = "", ParentOccupID = "335" });
            _AllCodes.Add(new ISCO() { OccupID = "3355", OccupName = "Police inspectors and detectives", OccupNameUkr = "", ParentOccupID = "335" });
            _AllCodes.Add(new ISCO() { OccupID = "3359", OccupName = "Regulatory government associate professionals not elsewhere", OccupNameUkr = "", ParentOccupID = "335" });
            _AllCodes.Add(new ISCO() { OccupID = "3411", OccupName = "Legal and related associate professionals", OccupNameUkr = "", ParentOccupID = "341" });
            _AllCodes.Add(new ISCO() { OccupID = "3412", OccupName = "Social work associate professionals", OccupNameUkr = "", ParentOccupID = "341" });
            _AllCodes.Add(new ISCO() { OccupID = "3413", OccupName = "Religious associate professionals", OccupNameUkr = "", ParentOccupID = "341" });
            _AllCodes.Add(new ISCO() { OccupID = "3421", OccupName = "Athletes and sports players", OccupNameUkr = "", ParentOccupID = "342" });
            _AllCodes.Add(new ISCO() { OccupID = "3422", OccupName = "Sports coaches, instructors and officials", OccupNameUkr = "", ParentOccupID = "342" });
            _AllCodes.Add(new ISCO() { OccupID = "3423", OccupName = "Fitness and recreation instructors and program leaders", OccupNameUkr = "", ParentOccupID = "342" });
            _AllCodes.Add(new ISCO() { OccupID = "3431", OccupName = "Photographers", OccupNameUkr = "", ParentOccupID = "343" });
            _AllCodes.Add(new ISCO() { OccupID = "3432", OccupName = "Interior designers and decorators", OccupNameUkr = "", ParentOccupID = "343" });
            _AllCodes.Add(new ISCO() { OccupID = "3433", OccupName = "Gallery, museum and library technicians", OccupNameUkr = "", ParentOccupID = "343" });
            _AllCodes.Add(new ISCO() { OccupID = "3434", OccupName = "Chefs", OccupNameUkr = "", ParentOccupID = "343" });
            _AllCodes.Add(new ISCO() { OccupID = "3435", OccupName = "Other artistic and cultural associate professionals", OccupNameUkr = "", ParentOccupID = "343" });
            _AllCodes.Add(new ISCO() { OccupID = "351", OccupName = "Information and communications technology operations and user support", OccupNameUkr = "", ParentOccupID = "35" });
            _AllCodes.Add(new ISCO() { OccupID = "3511", OccupName = "Information and communications technology operations", OccupNameUkr = "", ParentOccupID = "351" });
            _AllCodes.Add(new ISCO() { OccupID = "3512", OccupName = "Information and communications technology user support", OccupNameUkr = "", ParentOccupID = "351" });
            _AllCodes.Add(new ISCO() { OccupID = "3513", OccupName = "Computer network and systems technicians", OccupNameUkr = "", ParentOccupID = "351" });
            _AllCodes.Add(new ISCO() { OccupID = "3514", OccupName = "Web technicians", OccupNameUkr = "", ParentOccupID = "351" });
            _AllCodes.Add(new ISCO() { OccupID = "3521", OccupName = "Broadcasting and audio-visual technicians", OccupNameUkr = "", ParentOccupID = "352" });
            _AllCodes.Add(new ISCO() { OccupID = "3522", OccupName = "Telecommunications engineering technicians", OccupNameUkr = "", ParentOccupID = "352" });
            _AllCodes.Add(new ISCO() { OccupID = "4110", OccupName = "General office clerks", OccupNameUkr = "", ParentOccupID = "411" });
            _AllCodes.Add(new ISCO() { OccupID = "4120", OccupName = "Secretaries (general)", OccupNameUkr = "", ParentOccupID = "412" });
            _AllCodes.Add(new ISCO() { OccupID = "4131", OccupName = "Typists and word processing operators", OccupNameUkr = "", ParentOccupID = "413" });
            _AllCodes.Add(new ISCO() { OccupID = "4132", OccupName = "Data entry clerks", OccupNameUkr = "", ParentOccupID = "413" });
            _AllCodes.Add(new ISCO() { OccupID = "4211", OccupName = "Bank tellers and related clerks", OccupNameUkr = "", ParentOccupID = "421" });
            _AllCodes.Add(new ISCO() { OccupID = "4212", OccupName = "Bookmakers, croupiers and related gaming workers", OccupNameUkr = "", ParentOccupID = "421" });
            _AllCodes.Add(new ISCO() { OccupID = "4213", OccupName = "Pawnbrokers and money-lenders", OccupNameUkr = "", ParentOccupID = "421" });
            _AllCodes.Add(new ISCO() { OccupID = "4214", OccupName = "Debt-collectors and related workers", OccupNameUkr = "", ParentOccupID = "421" });
            _AllCodes.Add(new ISCO() { OccupID = "4221", OccupName = "Travel consultants and clerks", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4222", OccupName = "Contact centre information clerks", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4223", OccupName = "Telephone switchboard operators", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4224", OccupName = "Hotel receptionists", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4225", OccupName = "Enquiry clerks", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4226", OccupName = "Receptionists (general)", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4227", OccupName = "Survey and market research interviewers", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4229", OccupName = "Client information workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "422" });
            _AllCodes.Add(new ISCO() { OccupID = "4311", OccupName = "Accounting and bookkeeping clerks", OccupNameUkr = "", ParentOccupID = "431" });
            _AllCodes.Add(new ISCO() { OccupID = "4312", OccupName = "Statistical, finance and insurance clerks", OccupNameUkr = "", ParentOccupID = "431" });
            _AllCodes.Add(new ISCO() { OccupID = "4313", OccupName = "Payroll clerks", OccupNameUkr = "", ParentOccupID = "431" });
            _AllCodes.Add(new ISCO() { OccupID = "4321", OccupName = "Stock clerks", OccupNameUkr = "", ParentOccupID = "432" });
            _AllCodes.Add(new ISCO() { OccupID = "4322", OccupName = "Production clerks", OccupNameUkr = "", ParentOccupID = "432" });
            _AllCodes.Add(new ISCO() { OccupID = "4323", OccupName = "Transport clerks", OccupNameUkr = "", ParentOccupID = "432" });
            _AllCodes.Add(new ISCO() { OccupID = "4411", OccupName = "Library clerks", OccupNameUkr = "", ParentOccupID = "441" });
            _AllCodes.Add(new ISCO() { OccupID = "4412", OccupName = "Mail carriers and sorting clerks", OccupNameUkr = "", ParentOccupID = "441" });
            _AllCodes.Add(new ISCO() { OccupID = "4413", OccupName = "Coding, proof-reading and related clerks", OccupNameUkr = "", ParentOccupID = "441" });
            _AllCodes.Add(new ISCO() { OccupID = "4414", OccupName = "Scribes and related workers", OccupNameUkr = "", ParentOccupID = "441" });
            _AllCodes.Add(new ISCO() { OccupID = "4415", OccupName = "Filing and copying clerks", OccupNameUkr = "", ParentOccupID = "441" });
            _AllCodes.Add(new ISCO() { OccupID = "4416", OccupName = "Personnel clerks", OccupNameUkr = "", ParentOccupID = "441" });
            _AllCodes.Add(new ISCO() { OccupID = "4419", OccupName = "Clerical support workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "441" });
            _AllCodes.Add(new ISCO() { OccupID = "5111", OccupName = "Travel attendants and travel stewards", OccupNameUkr = "", ParentOccupID = "511" });
            _AllCodes.Add(new ISCO() { OccupID = "5112", OccupName = "Transport conductors", OccupNameUkr = "", ParentOccupID = "511" });
            _AllCodes.Add(new ISCO() { OccupID = "5113", OccupName = "Travel guides", OccupNameUkr = "", ParentOccupID = "511" });
            _AllCodes.Add(new ISCO() { OccupID = "5120", OccupName = "Cooks", OccupNameUkr = "", ParentOccupID = "512" });
            _AllCodes.Add(new ISCO() { OccupID = "5131", OccupName = "Waiters", OccupNameUkr = "", ParentOccupID = "513" });
            _AllCodes.Add(new ISCO() { OccupID = "5132", OccupName = "Bartenders", OccupNameUkr = "", ParentOccupID = "513" });
            _AllCodes.Add(new ISCO() { OccupID = "5141", OccupName = "Hairdressers", OccupNameUkr = "", ParentOccupID = "514" });
            _AllCodes.Add(new ISCO() { OccupID = "5142", OccupName = "Beauticians and related workers", OccupNameUkr = "", ParentOccupID = "514" });
            _AllCodes.Add(new ISCO() { OccupID = "5151", OccupName = "Cleaning and housekeeping supervisors in offices, hotels and", OccupNameUkr = "", ParentOccupID = "515" });
            _AllCodes.Add(new ISCO() { OccupID = "5152", OccupName = "Domestic housekeepers", OccupNameUkr = "", ParentOccupID = "515" });
            _AllCodes.Add(new ISCO() { OccupID = "5153", OccupName = "Building caretakers", OccupNameUkr = "", ParentOccupID = "515" });
            _AllCodes.Add(new ISCO() { OccupID = "5161", OccupName = "Astrologers, fortune-tellers and related workers", OccupNameUkr = "", ParentOccupID = "516" });
            _AllCodes.Add(new ISCO() { OccupID = "5162", OccupName = "Companions and valets", OccupNameUkr = "", ParentOccupID = "516" });
            _AllCodes.Add(new ISCO() { OccupID = "5163", OccupName = "Undertakers and embalmers", OccupNameUkr = "", ParentOccupID = "516" });
            _AllCodes.Add(new ISCO() { OccupID = "5164", OccupName = "Pet groomers and animal care workers", OccupNameUkr = "", ParentOccupID = "516" });
            _AllCodes.Add(new ISCO() { OccupID = "5165", OccupName = "Driving instructors", OccupNameUkr = "", ParentOccupID = "516" });
            _AllCodes.Add(new ISCO() { OccupID = "5169", OccupName = "Personal services workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "516" });
            _AllCodes.Add(new ISCO() { OccupID = "5211", OccupName = "Stall and market salespersons", OccupNameUkr = "", ParentOccupID = "521" });
            _AllCodes.Add(new ISCO() { OccupID = "5212", OccupName = "Street food salespersons", OccupNameUkr = "", ParentOccupID = "521" });
            _AllCodes.Add(new ISCO() { OccupID = "5221", OccupName = "Shop keepers", OccupNameUkr = "", ParentOccupID = "522" });
            _AllCodes.Add(new ISCO() { OccupID = "5222", OccupName = "Shop supervisors", OccupNameUkr = "", ParentOccupID = "522" });
            _AllCodes.Add(new ISCO() { OccupID = "5223", OccupName = "Shop sales assistants", OccupNameUkr = "", ParentOccupID = "522" });
            _AllCodes.Add(new ISCO() { OccupID = "5230", OccupName = "Cashiers and ticket clerks", OccupNameUkr = "", ParentOccupID = "523" });
            _AllCodes.Add(new ISCO() { OccupID = "5241", OccupName = "Fashion and other models", OccupNameUkr = "", ParentOccupID = "524" });
            _AllCodes.Add(new ISCO() { OccupID = "5242", OccupName = "Sales demonstrators", OccupNameUkr = "", ParentOccupID = "524" });
            _AllCodes.Add(new ISCO() { OccupID = "5243", OccupName = "Door to door salespersons", OccupNameUkr = "", ParentOccupID = "524" });
            _AllCodes.Add(new ISCO() { OccupID = "5244", OccupName = "Contact centre salespersons", OccupNameUkr = "", ParentOccupID = "524" });
            _AllCodes.Add(new ISCO() { OccupID = "5245", OccupName = "Service station attendants", OccupNameUkr = "", ParentOccupID = "524" });
            _AllCodes.Add(new ISCO() { OccupID = "5249", OccupName = "Sales workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "524" });
            _AllCodes.Add(new ISCO() { OccupID = "26", OccupName = "Resolution Concerning Updating ISCO", OccupNameUkr = "", ParentOccupID = "2" });
            _AllCodes.Add(new ISCO() { OccupID = "5311", OccupName = "Child care workers", OccupNameUkr = "", ParentOccupID = "531" });
            _AllCodes.Add(new ISCO() { OccupID = "5312", OccupName = "Teachers' aides", OccupNameUkr = "", ParentOccupID = "531" });
            _AllCodes.Add(new ISCO() { OccupID = "5321", OccupName = "Health care assistants", OccupNameUkr = "", ParentOccupID = "532" });
            _AllCodes.Add(new ISCO() { OccupID = "5322", OccupName = "Home-based personal care workers", OccupNameUkr = "", ParentOccupID = "532" });
            _AllCodes.Add(new ISCO() { OccupID = "5329", OccupName = "Personal care workers in health services not elsewhere classified", OccupNameUkr = "", ParentOccupID = "532" });
            _AllCodes.Add(new ISCO() { OccupID = "5411", OccupName = "Fire-fighters", OccupNameUkr = "", ParentOccupID = "541" });
            _AllCodes.Add(new ISCO() { OccupID = "5412", OccupName = "Police officers", OccupNameUkr = "", ParentOccupID = "541" });
            _AllCodes.Add(new ISCO() { OccupID = "5413", OccupName = "Prison guards", OccupNameUkr = "", ParentOccupID = "541" });
            _AllCodes.Add(new ISCO() { OccupID = "5414", OccupName = "Security guards", OccupNameUkr = "", ParentOccupID = "541" });
            _AllCodes.Add(new ISCO() { OccupID = "5419", OccupName = "Protective services workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "541" });
            _AllCodes.Add(new ISCO() { OccupID = "6111", OccupName = "Field crop and vegetable growers", OccupNameUkr = "", ParentOccupID = "611" });
            _AllCodes.Add(new ISCO() { OccupID = "6112", OccupName = "Tree and shrub crop growers", OccupNameUkr = "", ParentOccupID = "611" });
            _AllCodes.Add(new ISCO() { OccupID = "6113", OccupName = "Gardeners, horticultural and nursery growers", OccupNameUkr = "", ParentOccupID = "611" });
            _AllCodes.Add(new ISCO() { OccupID = "6114", OccupName = "Mixed crop growers", OccupNameUkr = "", ParentOccupID = "611" });
            _AllCodes.Add(new ISCO() { OccupID = "6121", OccupName = "Livestock and dairy producers", OccupNameUkr = "", ParentOccupID = "612" });
            _AllCodes.Add(new ISCO() { OccupID = "6122", OccupName = "Poultry producers", OccupNameUkr = "", ParentOccupID = "612" });
            _AllCodes.Add(new ISCO() { OccupID = "6123", OccupName = "Apiarists and sericulturists", OccupNameUkr = "", ParentOccupID = "612" });
            _AllCodes.Add(new ISCO() { OccupID = "6129", OccupName = "Animal producers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "612" });
            _AllCodes.Add(new ISCO() { OccupID = "6130", OccupName = "Mixed crop and animal producers", OccupNameUkr = "", ParentOccupID = "613" });
            _AllCodes.Add(new ISCO() { OccupID = "6210", OccupName = "Forestry and related workers", OccupNameUkr = "", ParentOccupID = "621" });
            _AllCodes.Add(new ISCO() { OccupID = "6221", OccupName = "Aquaculture workers", OccupNameUkr = "", ParentOccupID = "622" });
            _AllCodes.Add(new ISCO() { OccupID = "6222", OccupName = "Inland and coastal waters fishery workers", OccupNameUkr = "", ParentOccupID = "622" });
            _AllCodes.Add(new ISCO() { OccupID = "6223", OccupName = "Deep-sea fishery workers", OccupNameUkr = "", ParentOccupID = "622" });
            _AllCodes.Add(new ISCO() { OccupID = "6224", OccupName = "Hunters and trappers", OccupNameUkr = "", ParentOccupID = "622" });
            _AllCodes.Add(new ISCO() { OccupID = "6310", OccupName = "Subsistence crop farmers", OccupNameUkr = "", ParentOccupID = "631" });
            _AllCodes.Add(new ISCO() { OccupID = "6320", OccupName = "Subsistence livestock farmers", OccupNameUkr = "", ParentOccupID = "632" });
            _AllCodes.Add(new ISCO() { OccupID = "6330", OccupName = "Subsistence mixed crop and livestock farmers", OccupNameUkr = "", ParentOccupID = "633" });
            _AllCodes.Add(new ISCO() { OccupID = "6340", OccupName = "Subsistence fishers, hunters, trappers and gatherers", OccupNameUkr = "", ParentOccupID = "634" });
            _AllCodes.Add(new ISCO() { OccupID = "7111", OccupName = "House builders", OccupNameUkr = "", ParentOccupID = "711" });
            _AllCodes.Add(new ISCO() { OccupID = "7112", OccupName = "Bricklayers and related workers", OccupNameUkr = "", ParentOccupID = "711" });
            _AllCodes.Add(new ISCO() { OccupID = "7113", OccupName = "Stonemasons, stone cutters, splitters and carvers", OccupNameUkr = "", ParentOccupID = "711" });
            _AllCodes.Add(new ISCO() { OccupID = "7114", OccupName = "Concrete placers, concrete finishers and related workers", OccupNameUkr = "", ParentOccupID = "711" });
            _AllCodes.Add(new ISCO() { OccupID = "7115", OccupName = "Carpenters and joiners", OccupNameUkr = "", ParentOccupID = "711" });
            _AllCodes.Add(new ISCO() { OccupID = "7119", OccupName = "Building frame and related trades workers not elsewhere", OccupNameUkr = "", ParentOccupID = "711" });
            _AllCodes.Add(new ISCO() { OccupID = "7121", OccupName = "Roofers", OccupNameUkr = "", ParentOccupID = "712" });
            _AllCodes.Add(new ISCO() { OccupID = "7122", OccupName = "Floor layers and tile setters", OccupNameUkr = "", ParentOccupID = "712" });
            _AllCodes.Add(new ISCO() { OccupID = "7123", OccupName = "Plasterers", OccupNameUkr = "", ParentOccupID = "712" });
            _AllCodes.Add(new ISCO() { OccupID = "7124", OccupName = "Insulation workers", OccupNameUkr = "", ParentOccupID = "712" });
            _AllCodes.Add(new ISCO() { OccupID = "7125", OccupName = "Glaziers", OccupNameUkr = "", ParentOccupID = "712" });
            _AllCodes.Add(new ISCO() { OccupID = "7126", OccupName = "Plumbers and pipe fitters", OccupNameUkr = "", ParentOccupID = "712" });
            _AllCodes.Add(new ISCO() { OccupID = "7127", OccupName = "Air conditioning and refrigeration mechanics", OccupNameUkr = "", ParentOccupID = "712" });
            _AllCodes.Add(new ISCO() { OccupID = "7131", OccupName = "Painters and related workers", OccupNameUkr = "", ParentOccupID = "713" });
            _AllCodes.Add(new ISCO() { OccupID = "7132", OccupName = "Spray painters and varnishers", OccupNameUkr = "", ParentOccupID = "713" });
            _AllCodes.Add(new ISCO() { OccupID = "7133", OccupName = "Building structure cleaners", OccupNameUkr = "", ParentOccupID = "713" });
            _AllCodes.Add(new ISCO() { OccupID = "721", OccupName = "Sheet and structural metal workers, moulders and welders, and related", OccupNameUkr = "", ParentOccupID = "72" });
            _AllCodes.Add(new ISCO() { OccupID = "7211", OccupName = "Metal moulders and coremakers", OccupNameUkr = "", ParentOccupID = "721" });
            _AllCodes.Add(new ISCO() { OccupID = "7212", OccupName = "Welders and flamecutters", OccupNameUkr = "", ParentOccupID = "721" });
            _AllCodes.Add(new ISCO() { OccupID = "7213", OccupName = "Sheet-metal workers", OccupNameUkr = "", ParentOccupID = "721" });
            _AllCodes.Add(new ISCO() { OccupID = "7214", OccupName = "Structural-metal preparers and erectors", OccupNameUkr = "", ParentOccupID = "721" });
            _AllCodes.Add(new ISCO() { OccupID = "7215", OccupName = "Riggers and cable splicers", OccupNameUkr = "", ParentOccupID = "721" });
            _AllCodes.Add(new ISCO() { OccupID = "7221", OccupName = "Blacksmiths, hammersmiths and forging press workers", OccupNameUkr = "", ParentOccupID = "722" });
            _AllCodes.Add(new ISCO() { OccupID = "7222", OccupName = "Toolmakers and related workers", OccupNameUkr = "", ParentOccupID = "722" });
            _AllCodes.Add(new ISCO() { OccupID = "7223", OccupName = "Metal working machine tool setters and operators", OccupNameUkr = "", ParentOccupID = "722" });
            _AllCodes.Add(new ISCO() { OccupID = "7224", OccupName = "Metal polishers, wheel grinders and tool sharpeners", OccupNameUkr = "", ParentOccupID = "722" });
            _AllCodes.Add(new ISCO() { OccupID = "7231", OccupName = "Motor vehicle mechanics and repairers", OccupNameUkr = "", ParentOccupID = "723" });
            _AllCodes.Add(new ISCO() { OccupID = "7232", OccupName = "Aircraft engine mechanics and repairers", OccupNameUkr = "", ParentOccupID = "723" });
            _AllCodes.Add(new ISCO() { OccupID = "7233", OccupName = "Agricultural and industrial machinery mechanics and repairers", OccupNameUkr = "", ParentOccupID = "723" });
            _AllCodes.Add(new ISCO() { OccupID = "7234", OccupName = "Bicycle and related repairers", OccupNameUkr = "", ParentOccupID = "723" });
            _AllCodes.Add(new ISCO() { OccupID = "7311", OccupName = "Precision-instrument makers and repairers", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7312", OccupName = "Musical instrument makers and tuners", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7313", OccupName = "Jewellery and precious-metal workers", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7314", OccupName = "Potters and related workers", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7315", OccupName = "Glass makers, cutters, grinders and finishers", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7316", OccupName = "Sign writers, decorative painters, engravers and etchers", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7317", OccupName = "Handicraft workers in wood, basketry and related materials", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7318", OccupName = "Handicraft workers in textile, leather and related materials", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7319", OccupName = "Handicraft workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "731" });
            _AllCodes.Add(new ISCO() { OccupID = "7321", OccupName = "Pre-press technicians", OccupNameUkr = "", ParentOccupID = "732" });
            _AllCodes.Add(new ISCO() { OccupID = "7322", OccupName = "Printers", OccupNameUkr = "", ParentOccupID = "732" });
            _AllCodes.Add(new ISCO() { OccupID = "7323", OccupName = "Print finishing and binding workers", OccupNameUkr = "", ParentOccupID = "732" });
            _AllCodes.Add(new ISCO() { OccupID = "7411", OccupName = "Building and related electricians", OccupNameUkr = "", ParentOccupID = "741" });
            _AllCodes.Add(new ISCO() { OccupID = "7412", OccupName = "Electrical mechanics and fitters", OccupNameUkr = "", ParentOccupID = "741" });
            _AllCodes.Add(new ISCO() { OccupID = "7413", OccupName = "Electrical line installers and repairers", OccupNameUkr = "", ParentOccupID = "741" });
            _AllCodes.Add(new ISCO() { OccupID = "7421", OccupName = "Electronics mechanics and servicers", OccupNameUkr = "", ParentOccupID = "742" });
            _AllCodes.Add(new ISCO() { OccupID = "7422", OccupName = "Information and communications technology installers and", OccupNameUkr = "", ParentOccupID = "742" });
            _AllCodes.Add(new ISCO() { OccupID = "75", OccupName = "Food processing, wood working, garment and other craft and related trades", OccupNameUkr = "", ParentOccupID = "7" });
            _AllCodes.Add(new ISCO() { OccupID = "7511", OccupName = "Butchers, fishmongers and related food preparers", OccupNameUkr = "", ParentOccupID = "751" });
            _AllCodes.Add(new ISCO() { OccupID = "7512", OccupName = "Bakers, pastry-cooks and confectionery makers", OccupNameUkr = "", ParentOccupID = "751" });
            _AllCodes.Add(new ISCO() { OccupID = "7513", OccupName = "Dairy-products makers", OccupNameUkr = "", ParentOccupID = "751" });
            _AllCodes.Add(new ISCO() { OccupID = "7514", OccupName = "Fruit, vegetable and related preservers", OccupNameUkr = "", ParentOccupID = "751" });
            _AllCodes.Add(new ISCO() { OccupID = "7515", OccupName = "Food and beverage tasters and graders", OccupNameUkr = "", ParentOccupID = "751" });
            _AllCodes.Add(new ISCO() { OccupID = "7516", OccupName = "Tobacco preparers and tobacco products makers", OccupNameUkr = "", ParentOccupID = "751" });
            _AllCodes.Add(new ISCO() { OccupID = "7521", OccupName = "Wood treaters", OccupNameUkr = "", ParentOccupID = "752" });
            _AllCodes.Add(new ISCO() { OccupID = "7522", OccupName = "Cabinet-makers and related workers", OccupNameUkr = "", ParentOccupID = "752" });
            _AllCodes.Add(new ISCO() { OccupID = "7523", OccupName = "Woodworking-machine tool setters and operators", OccupNameUkr = "", ParentOccupID = "752" });
            _AllCodes.Add(new ISCO() { OccupID = "7531", OccupName = "Tailors, dressmakers, furriers and hatters", OccupNameUkr = "", ParentOccupID = "753" });
            _AllCodes.Add(new ISCO() { OccupID = "7532", OccupName = "Garment and related pattern-makers and cutters", OccupNameUkr = "", ParentOccupID = "753" });
            _AllCodes.Add(new ISCO() { OccupID = "7533", OccupName = "Sewing, embroidery and related workers", OccupNameUkr = "", ParentOccupID = "753" });
            _AllCodes.Add(new ISCO() { OccupID = "7534", OccupName = "Upholsterers and related workers", OccupNameUkr = "", ParentOccupID = "753" });
            _AllCodes.Add(new ISCO() { OccupID = "7535", OccupName = "Pelt dressers, tanners and fellmongers", OccupNameUkr = "", ParentOccupID = "753" });
            _AllCodes.Add(new ISCO() { OccupID = "7536", OccupName = "Shoemakers and related workers", OccupNameUkr = "", ParentOccupID = "753" });
            _AllCodes.Add(new ISCO() { OccupID = "7541", OccupName = "Underwater divers", OccupNameUkr = "", ParentOccupID = "754" });
            _AllCodes.Add(new ISCO() { OccupID = "7542", OccupName = "Shotfirers and blasters", OccupNameUkr = "", ParentOccupID = "754" });
            _AllCodes.Add(new ISCO() { OccupID = "7543", OccupName = "Product graders and testers (excluding foods and beverages)", OccupNameUkr = "", ParentOccupID = "754" });
            _AllCodes.Add(new ISCO() { OccupID = "7544", OccupName = "Fumigators and other pest and weed controllers", OccupNameUkr = "", ParentOccupID = "754" });
            _AllCodes.Add(new ISCO() { OccupID = "7549", OccupName = "Craft and related workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "754" });
            _AllCodes.Add(new ISCO() { OccupID = "8111", OccupName = "Miners and quarriers", OccupNameUkr = "", ParentOccupID = "811" });
            _AllCodes.Add(new ISCO() { OccupID = "8112", OccupName = "Mineral and stone processing plant operators", OccupNameUkr = "", ParentOccupID = "811" });
            _AllCodes.Add(new ISCO() { OccupID = "8113", OccupName = "Well drillers and borers and related workers", OccupNameUkr = "", ParentOccupID = "811" });
            _AllCodes.Add(new ISCO() { OccupID = "8114", OccupName = "Cement, stone and other mineral products machine operators", OccupNameUkr = "", ParentOccupID = "811" });
            _AllCodes.Add(new ISCO() { OccupID = "8121", OccupName = "Metal processing plant operators", OccupNameUkr = "", ParentOccupID = "812" });
            _AllCodes.Add(new ISCO() { OccupID = "8122", OccupName = "Metal finishing, plating and coating machine operators", OccupNameUkr = "", ParentOccupID = "812" });
            _AllCodes.Add(new ISCO() { OccupID = "8131", OccupName = "Chemical products plant and machine operators", OccupNameUkr = "", ParentOccupID = "813" });
            _AllCodes.Add(new ISCO() { OccupID = "8132", OccupName = "Photographic products machine operators", OccupNameUkr = "", ParentOccupID = "813" });
            _AllCodes.Add(new ISCO() { OccupID = "8141", OccupName = "Rubber products machine operators", OccupNameUkr = "", ParentOccupID = "814" });
            _AllCodes.Add(new ISCO() { OccupID = "8142", OccupName = "Plastic products machine operators", OccupNameUkr = "", ParentOccupID = "814" });
            _AllCodes.Add(new ISCO() { OccupID = "8143", OccupName = "Paper products machine operators", OccupNameUkr = "", ParentOccupID = "814" });
            _AllCodes.Add(new ISCO() { OccupID = "8151", OccupName = "Fibre preparing, spinning and winding machine operators", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8152", OccupName = "Weaving and knitting machine operators", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8153", OccupName = "Sewing machine operators", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8154", OccupName = "Bleaching, dyeing and fabric cleaning machine operators", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8155", OccupName = "Fur and leather preparing machine operators", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8156", OccupName = "Shoemaking and related machine operators", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8157", OccupName = "Laundry machine operators", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8159", OccupName = "Textile, fur and leather products machine operators not elsewhere", OccupNameUkr = "", ParentOccupID = "815" });
            _AllCodes.Add(new ISCO() { OccupID = "8160", OccupName = "Food and related products machine operators", OccupNameUkr = "", ParentOccupID = "816" });
            _AllCodes.Add(new ISCO() { OccupID = "8171", OccupName = "Pulp and papermaking plant operators", OccupNameUkr = "", ParentOccupID = "817" });
            _AllCodes.Add(new ISCO() { OccupID = "8172", OccupName = "Wood processing plant operators", OccupNameUkr = "", ParentOccupID = "817" });
            _AllCodes.Add(new ISCO() { OccupID = "8181", OccupName = "Glass and ceramics plant operators", OccupNameUkr = "", ParentOccupID = "818" });
            _AllCodes.Add(new ISCO() { OccupID = "8182", OccupName = "Steam engine and boiler operators", OccupNameUkr = "", ParentOccupID = "818" });
            _AllCodes.Add(new ISCO() { OccupID = "8183", OccupName = "Packing, bottling and labelling machine operators", OccupNameUkr = "", ParentOccupID = "818" });
            _AllCodes.Add(new ISCO() { OccupID = "8189", OccupName = "Stationary plant and machine operators not elsewhere classified", OccupNameUkr = "", ParentOccupID = "818" });
            _AllCodes.Add(new ISCO() { OccupID = "8211", OccupName = "Mechanical machinery assemblers", OccupNameUkr = "", ParentOccupID = "821" });
            _AllCodes.Add(new ISCO() { OccupID = "8212", OccupName = "Electrical and electronic equipment assemblers", OccupNameUkr = "", ParentOccupID = "821" });
            _AllCodes.Add(new ISCO() { OccupID = "8219", OccupName = "Assemblers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "821" });
            _AllCodes.Add(new ISCO() { OccupID = "32", OccupName = "Resolution Concerning Updating ISCO", OccupNameUkr = "", ParentOccupID = "3" });
            _AllCodes.Add(new ISCO() { OccupID = "8311", OccupName = "Locomotive engine drivers", OccupNameUkr = "", ParentOccupID = "831" });
            _AllCodes.Add(new ISCO() { OccupID = "8312", OccupName = "Railway brake, signal and switch operators", OccupNameUkr = "", ParentOccupID = "831" });
            _AllCodes.Add(new ISCO() { OccupID = "8321", OccupName = "Motorcycle drivers", OccupNameUkr = "", ParentOccupID = "832" });
            _AllCodes.Add(new ISCO() { OccupID = "8322", OccupName = "Car, taxi and van drivers", OccupNameUkr = "", ParentOccupID = "832" });
            _AllCodes.Add(new ISCO() { OccupID = "8331", OccupName = "Bus and tram drivers", OccupNameUkr = "", ParentOccupID = "833" });
            _AllCodes.Add(new ISCO() { OccupID = "8332", OccupName = "Heavy truck and lorry drivers", OccupNameUkr = "", ParentOccupID = "833" });
            _AllCodes.Add(new ISCO() { OccupID = "8341", OccupName = "Mobile farm and forestry plant operators", OccupNameUkr = "", ParentOccupID = "834" });
            _AllCodes.Add(new ISCO() { OccupID = "8342", OccupName = "Earthmoving and related plant operators", OccupNameUkr = "", ParentOccupID = "834" });
            _AllCodes.Add(new ISCO() { OccupID = "8343", OccupName = "Crane, hoist and related plant operators", OccupNameUkr = "", ParentOccupID = "834" });
            _AllCodes.Add(new ISCO() { OccupID = "8344", OccupName = "Lifting truck operators", OccupNameUkr = "", ParentOccupID = "834" });
            _AllCodes.Add(new ISCO() { OccupID = "8350", OccupName = "Ships' deck crews and related workers", OccupNameUkr = "", ParentOccupID = "835" });
            _AllCodes.Add(new ISCO() { OccupID = "9111", OccupName = "Domestic cleaners and helpers", OccupNameUkr = "", ParentOccupID = "911" });
            _AllCodes.Add(new ISCO() { OccupID = "9112", OccupName = "Cleaners and helpers in offices, hotels and other establishments", OccupNameUkr = "", ParentOccupID = "911" });
            _AllCodes.Add(new ISCO() { OccupID = "9121", OccupName = "Hand launderers and pressers", OccupNameUkr = "", ParentOccupID = "912" });
            _AllCodes.Add(new ISCO() { OccupID = "9122", OccupName = "Vehicle cleaners", OccupNameUkr = "", ParentOccupID = "912" });
            _AllCodes.Add(new ISCO() { OccupID = "9123", OccupName = "Window cleaners", OccupNameUkr = "", ParentOccupID = "912" });
            _AllCodes.Add(new ISCO() { OccupID = "9129", OccupName = "Other cleaning workers", OccupNameUkr = "", ParentOccupID = "912" });
            _AllCodes.Add(new ISCO() { OccupID = "9211", OccupName = "Crop farm labourers", OccupNameUkr = "", ParentOccupID = "921" });
            _AllCodes.Add(new ISCO() { OccupID = "9212", OccupName = "Livestock farm labourers", OccupNameUkr = "", ParentOccupID = "921" });
            _AllCodes.Add(new ISCO() { OccupID = "9213", OccupName = "Mixed crop and livestock farm labourers", OccupNameUkr = "", ParentOccupID = "921" });
            _AllCodes.Add(new ISCO() { OccupID = "9214", OccupName = "Garden and horticultural labourers", OccupNameUkr = "", ParentOccupID = "921" });
            _AllCodes.Add(new ISCO() { OccupID = "9215", OccupName = "Forestry labourers", OccupNameUkr = "", ParentOccupID = "921" });
            _AllCodes.Add(new ISCO() { OccupID = "9216", OccupName = "Fishery and aquaculture labourers", OccupNameUkr = "", ParentOccupID = "921" });
            _AllCodes.Add(new ISCO() { OccupID = "9311", OccupName = "Mining and quarrying labourers", OccupNameUkr = "", ParentOccupID = "931" });
            _AllCodes.Add(new ISCO() { OccupID = "9312", OccupName = "Civil engineering labourers", OccupNameUkr = "", ParentOccupID = "931" });
            _AllCodes.Add(new ISCO() { OccupID = "9313", OccupName = "Building construction labourers", OccupNameUkr = "", ParentOccupID = "931" });
            _AllCodes.Add(new ISCO() { OccupID = "9321", OccupName = "Hand packers", OccupNameUkr = "", ParentOccupID = "932" });
            _AllCodes.Add(new ISCO() { OccupID = "9329", OccupName = "Manufacturing labourers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "932" });
            _AllCodes.Add(new ISCO() { OccupID = "9331", OccupName = "Hand and pedal vehicle drivers", OccupNameUkr = "", ParentOccupID = "933" });
            _AllCodes.Add(new ISCO() { OccupID = "9332", OccupName = "Drivers of animal-drawn vehicles and machinery", OccupNameUkr = "", ParentOccupID = "933" });
            _AllCodes.Add(new ISCO() { OccupID = "9333", OccupName = "Freight handlers", OccupNameUkr = "", ParentOccupID = "933" });
            _AllCodes.Add(new ISCO() { OccupID = "9334", OccupName = "Shelf fillers", OccupNameUkr = "", ParentOccupID = "933" });
            _AllCodes.Add(new ISCO() { OccupID = "9411", OccupName = "Fast food preparers", OccupNameUkr = "", ParentOccupID = "941" });
            _AllCodes.Add(new ISCO() { OccupID = "9412", OccupName = "Kitchen helpers", OccupNameUkr = "", ParentOccupID = "941" });
            _AllCodes.Add(new ISCO() { OccupID = "9510", OccupName = "Street and related service workers", OccupNameUkr = "", ParentOccupID = "951" });
            _AllCodes.Add(new ISCO() { OccupID = "9520", OccupName = "Street vendors (excluding food)", OccupNameUkr = "", ParentOccupID = "952" });
            _AllCodes.Add(new ISCO() { OccupID = "9611", OccupName = "Garbage and recycling collectors", OccupNameUkr = "", ParentOccupID = "961" });
            _AllCodes.Add(new ISCO() { OccupID = "9612", OccupName = "Refuse sorters", OccupNameUkr = "", ParentOccupID = "961" });
            _AllCodes.Add(new ISCO() { OccupID = "9613", OccupName = "Sweepers and related labourers", OccupNameUkr = "", ParentOccupID = "961" });
            _AllCodes.Add(new ISCO() { OccupID = "9621", OccupName = "Messengers, package deliverers and luggage porters", OccupNameUkr = "", ParentOccupID = "962" });
            _AllCodes.Add(new ISCO() { OccupID = "9622", OccupName = "Odd job persons", OccupNameUkr = "", ParentOccupID = "962" });
            _AllCodes.Add(new ISCO() { OccupID = "9623", OccupName = "Meter readers and vending-machine collectors", OccupNameUkr = "", ParentOccupID = "962" });
            _AllCodes.Add(new ISCO() { OccupID = "9624", OccupName = "Water and firewood collectors", OccupNameUkr = "", ParentOccupID = "962" });
            _AllCodes.Add(new ISCO() { OccupID = "9629", OccupName = "Elementary workers not elsewhere classified", OccupNameUkr = "", ParentOccupID = "962" });
            _AllCodes.Add(new ISCO() { OccupID = "0110", OccupName = "Commissioned armed forces officers", OccupNameUkr = "", ParentOccupID = "011" });
            _AllCodes.Add(new ISCO() { OccupID = "0210", OccupName = "Non-commissioned armed forces officers", OccupNameUkr = "", ParentOccupID = "021" });
            _AllCodes.Add(new ISCO() { OccupID = "0310", OccupName = "Armed forces occupations, other ranks", OccupNameUkr = "", ParentOccupID = "031" });
            #endregion
        }
        #endregion

        public static List<ISCO> AllCodes
        {
            get
            {
                return _AllCodes;
            }
        }
        #endregion
    }
}
