//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGU.DRPL.SignificantOwnership.Utility.XAMLTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XAMLPrimitiveTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XAMLPrimitiveTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BGU.DRPL.SignificantOwnership.Utility.XAMLTemplates.XAMLPrimitiveTemplates", typeof(XAMLPrimitiveTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CheckBox Grid.Row=&quot;0&quot; Checked=&quot;{Binding yourPropertyName}&quot; FlowDirection=&quot;RightToLeft&quot;&gt;
        ///  &lt;TextBlock FlowDirection=&quot;LeftToRight&quot; Text=&quot;yourPropertyDisplayName:&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///&lt;/CheckBox&gt;
        ///.
        /// </summary>
        public static string _bool {
            get {
                return ResourceManager.GetString("_bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBlock Grid.Row=&quot;1&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot; /&gt;
        ///&lt;TextBox Grid.Row=&quot;2&quot; Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///.
        /// </summary>
        public static string _decimal {
            get {
                return ResourceManager.GetString("_decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBlock Grid.Row=&quot;5&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; /&gt;
        ///&lt;ComboBox Grid.Row=&quot;6&quot; ToolTip=&quot;yourPropertyDescription&quot; ItemsSource=&quot;{Binding Source={x:Static bgus:EnumsLister.yourEnumListerProperty}, Mode=OneWay}&quot; SelectedValue=&quot;{Binding yourPropertyName}&quot; DisplayMemberPath=&quot;Value&quot; SelectedValuePath=&quot;EnumValue&quot; HorizontalAlignment=&quot;Stretch&quot;/&gt;
        ///.
        /// </summary>
        public static string _enum {
            get {
                return ResourceManager.GetString("_enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBlock Grid.Row=&quot;1&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; /&gt;
        ///&lt;TextBox Grid.Row=&quot;2&quot; Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///.
        /// </summary>
        public static string _int {
            get {
                return ResourceManager.GetString("_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Expander Grid.Row=&quot;0&quot; Header=&quot;yourPropertyDispName&quot; ToolTip=&quot;yourPropertyDescription&quot; HorizontalAlignment=&quot;Stretch&quot; VerticalAlignment=&quot;Stretch&quot; Width=&quot;auto&quot; Height=&quot;auto&quot; IsExpanded=&quot;False&quot;&gt;
        ///  &lt;ContentControl Content=&quot;{Binding yourPropertyName}&quot; Margin=&quot;5,2&quot; /&gt;
        ///&lt;/Expander&gt;
        ///.
        /// </summary>
        public static string classstruct {
            get {
                return ResourceManager.GetString("classstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBlock Grid.Row=&quot;7&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot; /&gt;
        ///&lt;DatePicker Grid.Row=&quot;5&quot; ToolTip=&quot;yourPropertyDescription&quot;  Style=&quot;{StaticResource dtEdStyle}&quot; SelectedDate=&quot;{Binding yourPropertyName}&quot;/&gt;
        ///.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:local=&quot;clr-namespace:WpfApplication2&quot;
        ///                    xmlns:bgus=&quot;clr-namespace:BGU.DRPL.SignificantOwnership.Core.Spares;assembly=BGU.DRPL.SignificantOwnership.Core&quot;
        ///                    xmlns:bgusd=&quot;clr-namespace:BGU.DRPL.SignificantOwnership.Core.Spares.Data;assembly=BGU.DRPL.SignificantOwnership.Core&quot;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenericControlTemplate {
            get {
                return ResourceManager.GetString("GenericControlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Expander Grid.Row=&quot;0&quot; Header=&quot;yourPropertyDispName&quot; ToolTip=&quot;yourPropertyDescription&quot; HorizontalAlignment=&quot;Stretch&quot; VerticalAlignment=&quot;Stretch&quot; Width=&quot;auto&quot; Height=&quot;auto&quot; IsExpanded=&quot;False&quot;&gt;
        ///  &lt;DataGrid CanUserAddRows=&quot;True&quot; CanUserDeleteRows=&quot;True&quot; ItemsSource=&quot;{Binding yourPropertyName}&quot; AutoGenerateColumns=&quot;True&quot;&gt;&lt;/DataGrid&gt;
        ///&lt;/Expander&gt;
        ///.
        /// </summary>
        public static string ListOfT {
            get {
                return ResourceManager.GetString("ListOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBlock Grid.Row=&quot;3&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot; /&gt;
        ///&lt;TextBox Grid.Row=&quot;4&quot; Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName}&quot; ToolTip=&quot;yourPropertyDescription&quot; TextWrapping=&quot;Wrap&quot; AcceptsReturn=&quot;True&quot; VerticalAlignment=&quot;Stretch&quot; /&gt;
        ///.
        /// </summary>
        public static string multilinestring {
            get {
                return ResourceManager.GetString("multilinestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TextBlock Grid.Row=&quot;1&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///&lt;TextBox Grid.Row=&quot;2&quot; Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///.
        /// </summary>
        public static string onelinestring {
            get {
                return ResourceManager.GetString("onelinestring", resourceCulture);
            }
        }
    }
}
