//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGU.DRPL.SignificantOwnership.Utility.XAMLTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XAMLPrimitiveTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XAMLPrimitiveTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BGU.DRPL.SignificantOwnership.Utility.XAMLTemplates.XAMLPrimitiveTemplates", typeof(XAMLPrimitiveTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///&lt;CheckBox IsChecked=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; FlowDirection=&quot;LeftToRight&quot;&gt;
        ///  &lt;TextBlock FlowDirection=&quot;LeftToRight&quot; Text=&quot;yourPropertyDispName:&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///&lt;/CheckBox&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string _bool {
            get {
                return ResourceManager.GetString("_bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot; /&gt;
        ///  &lt;TextBox Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string _decimal {
            get {
                return ResourceManager.GetString("_decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; /&gt;
        ///  &lt;ComboBox ToolTip=&quot;yourPropertyDescription&quot; ItemsSource=&quot;{Binding Source={x:Static bgus:EnumsLister.yourEnumListerProperty}, Mode=OneWay, diag:PresentationTraceSources.TraceLevel=High}&quot; SelectedValue=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; DisplayMemberPath=&quot;Value&quot; SelectedValuePath=&quot;EnumValue&quot; HorizontalAlignment=&quot;Stretch&quot;/&gt;
        ///&lt;/Template [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _enum {
            get {
                return ResourceManager.GetString("_enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; /&gt;
        ///  &lt;TextBox Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string _int {
            get {
                return ResourceManager.GetString("_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;Expander Header=&quot;yourCategoryName&quot; ToolTip=&quot;yourCategoryName&quot; HorizontalAlignment=&quot;Stretch&quot; VerticalAlignment=&quot;Stretch&quot; Width=&quot;auto&quot; Height=&quot;auto&quot; IsExpanded=&quot;False&quot;&gt;
        ///    &lt;StackPanel Orientation=&quot;Vertical&quot; Margin=&quot;5,2&quot;&gt;
        ///    &lt;/StackPanel&gt;
        ///  &lt;/Expander&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string CategoryExpander {
            get {
                return ResourceManager.GetString("CategoryExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;Expander Header=&quot;yourPropertyDispName&quot; ToolTip=&quot;yourPropertyDescription&quot; HorizontalAlignment=&quot;Stretch&quot; VerticalAlignment=&quot;Stretch&quot; Width=&quot;auto&quot; Height=&quot;auto&quot; IsExpanded=&quot;False&quot;&gt;
        ///    &lt;ContentControl Content=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; Margin=&quot;5,2&quot; /&gt;
        ///  &lt;/Expander&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string classstruct {
            get {
                return ResourceManager.GetString("classstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;Grid&gt;
        ///    &lt;Grid.ColumnDefinitions&gt;
        ///      &lt;ColumnDefinition Width=&quot;1*&quot; /&gt;
        ///      &lt;ColumnDefinition Width=&quot;4*&quot; /&gt;
        ///    &lt;/Grid.ColumnDefinitions&gt;
        ///    &lt;TextBlock Grid.Column=&quot;0&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot; HorizontalAlignment=&quot;Left&quot; VerticalAlignment=&quot;Top&quot; /&gt; &lt;ContentControl Grid.Column=&quot;1&quot; Content=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; Margin=&quot;5, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string classstruct_noExpander {
            get {
                return ResourceManager.GetString("classstruct_noExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///  &lt;StackPanel Orientation=&quot;Horizontal&quot;&gt;
        ///    &lt;TextBlock x:Name=&quot;lblyourPropertyName&quot; Height=&quot;auto&quot; Width=&quot;auto&quot; Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///    &lt;ComboBox x:Name=&quot;cbxyourPropertyName&quot; DisplayMemberPath=&quot;yourComboDisplayMember&quot; SelectedValuePath=&quot;ID&quot; HorizontalAlignment=&quot;Stretch&quot; SelectedValue=&quot;{Binding Acquiree, Mode=TwoWay, diag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ComboAddBtn {
            get {
                return ResourceManager.GetString("ComboAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;StackPanel Orientation=&quot;Horizontal&quot;&gt;
        ///    &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///    &lt;ComboBox ToolTip=&quot;yourPropertyDescription&quot; ItemsSource=&quot;{Binding Source={x:Static yourComboItemsGetter}, Mode=OneWay, diag:PresentationTraceSources.TraceLevel=High}&quot;  DisplayMemberPath=&quot;yourComboDisplayMember&quot; /&gt;
        ///  &lt;/StackPanel&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string ComboTemplate {
            get {
                return ResourceManager.GetString("ComboTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;DataGridTemplateColumn Header=&quot;дії&quot; Width=&quot;*&quot; TextBlock.TextAlignment=&quot;Center&quot;&gt;
        ///    &lt;DataGridTemplateColumn.HeaderStyle&gt;
        ///      &lt;Style TargetType=&quot;dataprimitives:DataGridColumnHeader&quot;&gt;
        ///        &lt;Setter Property=&quot;ContentTemplate&quot;&gt;
        ///          &lt;Setter.Value&gt;
        ///            &lt;DataTemplate&gt;
        ///              &lt;ContentControl Content=&quot;{Binding}&quot;&gt;
        ///                &lt;ToolTipService.ToolTip&gt;
        ///                  &lt;ToolTip Content=&quot;Натисніть ґудзик, щоб редагувати чи вида [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DataGridCommandsColumnTemplate {
            get {
                return ResourceManager.GetString("DataGridCommandsColumnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;DataGridTextColumn Binding=&quot;{Binding Path=yourPropertyName, diag:PresentationTraceSources.TraceLevel=High, Mode=TwoWay}&quot; Header=&quot;yourPropertyDispName&quot; Width=&quot;*&quot; TextBlock.TextAlignment=&quot;Center&quot;&gt;
        ///    &lt;DataGridTextColumn.HeaderStyle&gt;
        ///      &lt;Style TargetType=&quot;dataprimitives:DataGridColumnHeader&quot;&gt;
        ///        &lt;Setter Property=&quot;TextBlock.TextWrapping&quot; Value=&quot;Wrap&quot; /&gt;
        ///        &lt;Setter Property=&quot;TextBlock.TextAlignment&quot; Value=&quot;Center&quot;/&gt;
        ///        &lt;Setter Proper [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DataGridTextColumnTemplate {
            get {
                return ResourceManager.GetString("DataGridTextColumnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot; /&gt;
        ///  &lt;DatePicker ToolTip=&quot;yourPropertyDescription&quot;  Style=&quot;{StaticResource dtEdStyle}&quot; SelectedDate=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot;/&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:local=&quot;clr-namespace:WpfApplication2&quot;
        ///                    xmlns:bgus=&quot;clr-namespace:BGU.DRPL.SignificantOwnership.Core.Spares;assembly=BGU.DRPL.SignificantOwnership.Core&quot;
        ///                    xmlns:bgusd=&quot;clr-namespace:BGU.DRPL.SignificantOwnership.Core.Spares.Data;assembly=BGU.DRPL.SignificantOwnership.Core&quot;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenericControlTemplate {
            get {
                return ResourceManager.GetString("GenericControlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///  &lt;Expander Header=&quot;yourPropertyDispName&quot; ToolTip=&quot;yourPropertyDescription&quot; HorizontalAlignment=&quot;Stretch&quot; VerticalAlignment=&quot;Stretch&quot; Width=&quot;auto&quot; Height=&quot;auto&quot; IsExpanded=&quot;False&quot;&gt;
        ///    &lt;StackPanel HorizontalAlignment=&quot;Stretch&quot; VerticalAlignment=&quot;Stretch&quot; Width=&quot;auto&quot; Height=&quot;auto&quot; Orientation=&quot;Vertical&quot;&gt;
        ///      &lt;DataGrid x:Name=&quot;gridyourPropertyName&quot; CanUserAddRows=&quot;False&quot; CanUserDeleteRows=&quot;False&quot; I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ListOfT {
            get {
                return ResourceManager.GetString("ListOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot; /&gt;
        ///  &lt;TextBox Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; ToolTip=&quot;yourPropertyDescription&quot; TextWrapping=&quot;Wrap&quot; AcceptsReturn=&quot;True&quot; VerticalAlignment=&quot;Stretch&quot; Height=&quot;auto&quot; MaxHeight=&quot;60&quot; /&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string multilinestring {
            get {
                return ResourceManager.GetString("multilinestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///  &lt;TextBox Style=&quot;{StaticResource txtEdStyle}&quot; Text=&quot;{Binding yourPropertyName, diag:PresentationTraceSources.TraceLevel=High}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string onelinestring {
            get {
                return ResourceManager.GetString("onelinestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;RadioButton Content=&quot;yourEnumCurrentValueDescription&quot; GroupName=&quot;rbgyourPropertyName&quot; ToolTip=&quot;yourEnumCurrentValueText - yourEnumCurrentValueDescription&quot; IsChecked=&quot;{Binding Path=yourPropertyName, Mode=TwoWay, Converter={StaticResource enum2BoolConv}, ConverterParameter=yourEnumCurrentValueText}&quot; /&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Template&gt;
        ///  &lt;StackPanel&gt;
        ///    &lt;TextBlock Text=&quot;yourPropertyDispName&quot; Style=&quot;{StaticResource dispNmStyle}&quot; ToolTip=&quot;yourPropertyDescription&quot;/&gt;
        ///  &lt;/StackPanel&gt;
        ///&lt;/Template&gt;.
        /// </summary>
        public static string RadioButtonGroup {
            get {
                return ResourceManager.GetString("RadioButtonGroup", resourceCulture);
            }
        }
    }
}
