@echo off

SET PDF_PATH=%~1
SET TRIM_OVERLAPS=%~2
SET CHATTY=%~3
SET OUT_XTRECTS_PATH=%~4

IF "%TRIM_OVERLAPS%"=="" (SET TRIM_OVERLAPS=true)
IF "%CHATTY%"=="" (SET CHATTY=false)
IF "%OUT_XTRECTS_PATH%"=="" (SET LOG_PATH=%PDF_PATH%.xtrects.log) ELSE (SET LOG_PATH=%OUT_XTRECTS_PATH%.log)
IF "%OUT_XTRECTS_PATH%"=="" (SET OUT_XTRECTS_PATH=%LOG_PATH%.json)

..\bin\Debug\PDF2DataTest.exe ExtractTableRectangles "%PDF_PATH%" %TRIM_OVERLAPS% %CHATTY% "%OUT_XTRECTS_PATH%" 1> %LOG_PATH% 2>&1
